const CATEGORIES={
  histoire:{name:'Histoire',emoji:'📜'},geographie:{name:'Géographie',emoji:'🗺️'},sciences:{name:'Sciences',emoji:'🔬'},cinema:{name:'Cinéma & séries',emoji:'🎬'},
  jeux:{name:'Jeux vidéo',emoji:'🎮'},musique:{name:'Musique',emoji:'🎵'},tech:{name:'Tech',emoji:'💻'},sport:{name:'Sport',emoji:'🏆'},retro:{name:'Années 90/2000',emoji:'📼'},insolite:{name:'Insolite',emoji:'🤯'}
};
const DNAME={easy:'Facile',normal:'Normal',hard:'Difficile',expert:'Expert'};
const Q=(id,cat,diff,q,opts,a,ex)=>({id,cat,diff,q,opts,a,ex});
const QUESTIONS=[
Q('H01','histoire','easy','En quelle année débute la Révolution française ?',['1789','1815','1848','1914'],0,'La prise de la Bastille a lieu le 14 juillet 1789.'),
Q('H02','histoire','easy','En quelle année tombe le mur de Berlin ?',['1979','1985','1989','1991'],2,'Le mur de Berlin s’ouvre dans la nuit du 9 novembre 1989.'),
Q('H03','histoire','normal','Quel souverain devient empereur des Français en 1804 ?',['Louis XVI','Napoléon Bonaparte','Louis-Philippe','Charles X'],1,'Napoléon Ier est sacré empereur en décembre 1804.'),
Q('H04','histoire','normal','Quel événement met fin aux combats de la Première Guerre mondiale sur le front occidental ?',['Le traité de Versailles','L’armistice du 11 novembre 1918','La bataille de Verdun','La révolution russe'],1,'L’armistice est signé le 11 novembre 1918 ; le traité de Versailles viendra en 1919.'),
Q('H05','histoire','hard','En quelle année l’Empire romain d’Occident disparaît-il traditionnellement ?',['395','410','476','622'],2,'476 est la date traditionnelle de la fin de l’Empire romain d’Occident.'),
Q('H06','histoire','hard','Qui déchiffre les hiéroglyphes grâce notamment à la pierre de Rosette ?',['Howard Carter','Jean-François Champollion','Heinrich Schliemann','Auguste Mariette'],1,'Champollion annonce son déchiffrement en 1822.'),
Q('H07','histoire','expert','En quelle année la Magna Carta est-elle scellée en Angleterre ?',['1066','1215','1314','1453'],1,'La Magna Carta est scellée par le roi Jean en 1215.'),
Q('H08','histoire','expert','Quelle bataille de 1066 mène à la conquête normande de l’Angleterre ?',['Azincourt','Hastings','Bosworth','Crécy'],1,'Guillaume le Conquérant remporte la bataille d’Hastings en 1066.'),

Q('G01','geographie','easy','Quelle est la capitale de l’Australie ?',['Sydney','Melbourne','Canberra','Perth'],2,'Canberra est la capitale fédérale de l’Australie.'),
Q('G02','geographie','easy','Quel est le plus grand pays du monde par superficie ?',['Canada','Chine','États-Unis','Russie'],3,'La Russie est le plus vaste État du monde.'),
Q('G03','geographie','normal','Dans quel pays se trouve le Kilimandjaro ?',['Kenya','Tanzanie','Éthiopie','Ouganda'],1,'Le Kilimandjaro se situe dans le nord-est de la Tanzanie.'),
Q('G04','geographie','normal','Dans quel océan se trouve Madagascar ?',['Atlantique','Pacifique','Indien','Arctique'],2,'Madagascar est une île de l’océan Indien.'),
Q('G05','geographie','hard','Dans quelle mer se jette le Danube ?',['Mer Baltique','Mer Noire','Mer Adriatique','Mer Égée'],1,'Le Danube forme un vaste delta avant de se jeter dans la mer Noire.'),
Q('G06','geographie','hard','Quel détroit sépare principalement l’Espagne du Maroc ?',['Béring','Ormuz','Gibraltar','Malacca'],2,'Le détroit de Gibraltar relie Atlantique et Méditerranée.'),
Q('G07','geographie','expert','Dans quel pays se trouve le lac Baïkal ?',['Mongolie','Russie','Kazakhstan','Finlande'],1,'Le lac Baïkal se trouve en Sibérie, en Russie.'),
Q('G08','geographie','expert','Quel est le plus grand désert du monde si l’on inclut les déserts froids ?',['Sahara','Gobi','Antarctique','Arabie'],2,'L’Antarctique est un désert polaire et le plus vaste désert terrestre.'),

Q('S01','sciences','easy','Quelle est la formule chimique de l’eau ?',['CO₂','H₂O','O₂','NaCl'],1,'Une molécule d’eau contient deux atomes d’hydrogène et un d’oxygène.'),
Q('S02','sciences','easy','Combien de planètes compte le Système solaire ?',['7','8','9','10'],1,'Depuis le reclassement de Pluton en planète naine, il y a 8 planètes.'),
Q('S03','sciences','normal','Quel symbole chimique correspond à l’or ?',['Ag','Au','Fe','Or'],1,'Au vient du latin « aurum ».'),
Q('S04','sciences','normal','Quel est le pH d’une solution neutre à température ambiante ?',['0','5','7','14'],2,'Un pH de 7 est neutre dans les conditions usuelles.'),
Q('S05','sciences','hard','À environ quelle vitesse la lumière se propage-t-elle dans le vide ?',['30 000 km/s','300 000 km/s','3 000 000 km/s','1 080 km/s'],1,'La valeur exacte est 299 792 458 m/s, soit environ 300 000 km/s.'),
Q('S06','sciences','hard','Combien de bases azotées principales composent l’ADN ?',['2','3','4','5'],2,'Adénine, thymine, cytosine et guanine.'),
Q('S07','sciences','expert','Quel organite cellulaire produit l’essentiel de l’ATP lors de la respiration cellulaire ?',['Lysosome','Mitochondrie','Ribosome','Centrosome'],1,'Les mitochondries sont centrales dans la production d’ATP.'),
Q('S08','sciences','expert','À combien correspond approximativement le zéro absolu en degrés Celsius ?',['−100 °C','−173,15 °C','−273,15 °C','−373,15 °C'],2,'Le zéro absolu vaut 0 kelvin, soit −273,15 °C.'),

Q('C01','cinema','easy','Qui réalise « Jurassic Park » sorti en 1993 ?',['James Cameron','Steven Spielberg','Ridley Scott','George Lucas'],1,'Steven Spielberg réalise Jurassic Park.'),
Q('C02','cinema','easy','Comment s’appelle le professeur de chimie de « Breaking Bad » ?',['Jesse Pinkman','Walter White','Saul Goodman','Gus Fring'],1,'Walter White devient le personnage central de la série.'),
Q('C03','cinema','normal','Quelle voiture sert de machine à voyager dans le temps dans « Retour vers le futur » ?',['Ford Mustang','DeLorean DMC-12','Pontiac Firebird','Chevrolet Corvette'],1,'Doc transforme une DeLorean DMC-12 en machine temporelle.'),
Q('C04','cinema','normal','Dans quelle ville fictive vivent les héros de « Stranger Things » ?',['Sunnydale','Hawkins','Riverdale','Twin Peaks'],1,'La série se déroule principalement à Hawkins, dans l’Indiana.'),
Q('C05','cinema','hard','Qui a réalisé « Le Parrain » ?',['Martin Scorsese','Francis Ford Coppola','Brian De Palma','Sergio Leone'],1,'Francis Ford Coppola réalise Le Parrain, sorti en 1972.'),
Q('C06','cinema','hard','Qui a écrit le roman « Le Seigneur des anneaux » ?',['C. S. Lewis','J. R. R. Tolkien','George R. R. Martin','Terry Pratchett'],1,'J. R. R. Tolkien est l’auteur du Seigneur des anneaux.'),
Q('C07','cinema','expert','En quelle année le premier « Star Wars » sorti au cinéma, devenu l’Épisode IV, est-il lancé ?',['1975','1977','1979','1981'],1,'Star Wars sort pour la première fois en 1977.'),
Q('C08','cinema','expert','Qui a réalisé la trilogie originale de « Matrix » avec Lilly Wachowski ?',['Lana Wachowski','Kathryn Bigelow','Patty Jenkins','Sofia Coppola'],0,'Lana et Lilly Wachowski ont écrit et réalisé la trilogie originale.'),

Q('J01','jeux','easy','Quel est le nom du héros principal de la série « The Legend of Zelda » ?',['Zelda','Link','Ganondorf','Epona'],1,'Le joueur incarne principalement Link ; Zelda est la princesse.'),
Q('J02','jeux','easy','Quelle entreprise a créé Sonic ?',['Nintendo','Sega','Sony','Atari'],1,'Sonic est la mascotte historique de Sega.'),
Q('J03','jeux','normal','Quel créateur japonais est associé à Mario et The Legend of Zelda ?',['Hideo Kojima','Shigeru Miyamoto','Yu Suzuki','Satoru Iwata'],1,'Shigeru Miyamoto est l’un des créateurs majeurs de Nintendo.'),
Q('J04','jeux','normal','En quelle année le jeu « Doom » original est-il sorti ?',['1989','1991','1993','1996'],2,'Doom d’id Software sort en décembre 1993.'),
Q('J05','jeux','hard','Quel studio/éditeur japonais a créé Pac-Man ?',['Namco','Capcom','Konami','SNK'],0,'Pac-Man est créé par Namco et lancé en arcade en 1980.'),
Q('J06','jeux','hard','Qui est le créateur initial de Minecraft ?',['Gabe Newell','Markus Persson','John Carmack','Tim Sweeney'],1,'Markus « Notch » Persson crée la première version de Minecraft.'),
Q('J07','jeux','expert','Quels étaient les deux premiers jeux Pokémon commercialisés au Japon en 1996 ?',['Rouge et Bleu','Rouge et Vert','Or et Argent','Jaune et Bleu'],1,'Pokémon Rouge et Vert sortent au Japon en 1996.'),
Q('J08','jeux','expert','En quelle année la première PlayStation est-elle commercialisée en Europe ?',['1994','1995','1996','1997'],1,'La PlayStation arrive en Europe en septembre 1995.'),

Q('M01','musique','easy','Quel groupe vient de Liverpool ?',['The Beatles','ABBA','U2','Queen'],0,'Les Beatles se forment à Liverpool.'),
Q('M02','musique','easy','Qui chantait principalement avec Queen ?',['David Bowie','Freddie Mercury','Elton John','George Michael'],1,'Freddie Mercury est le chanteur emblématique de Queen.'),
Q('M03','musique','normal','De quel pays est originaire le duo Daft Punk ?',['Belgique','France','Royaume-Uni','Canada'],1,'Daft Punk est un duo français.'),
Q('M04','musique','normal','Qui interprète l’album « Thriller » ?',['Prince','Michael Jackson','Stevie Wonder','Lionel Richie'],1,'Thriller est un album de Michael Jackson sorti en 1982.'),
Q('M05','musique','hard','Quel groupe interprète « Smells Like Teen Spirit » ?',['Pearl Jam','Nirvana','Soundgarden','Radiohead'],1,'Le titre ouvre l’album Nevermind de Nirvana.'),
Q('M06','musique','hard','Quel groupe a sorti l’album « Abbey Road » ?',['The Rolling Stones','The Beatles','Pink Floyd','The Who'],1,'Abbey Road est un album des Beatles sorti en 1969.'),
Q('M07','musique','expert','Combien de symphonies numérotées Beethoven a-t-il achevées ?',['7','8','9','10'],2,'Beethoven a achevé neuf symphonies numérotées.'),
Q('M08','musique','expert','À quel pays Bob Marley est-il principalement associé par sa naissance et sa carrière ?',['Cuba','Jamaïque','Bahamas','Trinité-et-Tobago'],1,'Bob Marley est né en Jamaïque et est une figure majeure du reggae.'),

Q('T01','tech','easy','Que signifie HTML ?',['HyperText Markup Language','High Transfer Machine Link','Home Tool Markup Layer','Hyperlink Text Media Logic'],0,'HTML signifie HyperText Markup Language.'),
Q('T02','tech','easy','Quels chiffres utilise le système binaire ?',['0 et 1','1 et 2','0 à 9','A et B'],0,'Le binaire utilise deux états : 0 et 1.'),
Q('T03','tech','normal','Qui est à l’origine du noyau Linux ?',['Steve Wozniak','Linus Torvalds','Dennis Ritchie','Richard Stallman'],1,'Linus Torvalds commence le noyau Linux en 1991.'),
Q('T04','tech','normal','En quelle année le premier iPhone est-il commercialisé ?',['2005','2006','2007','2008'],2,'Le premier iPhone est commercialisé en 2007.'),
Q('T05','tech','hard','Qui a inventé le World Wide Web ?',['Vint Cerf','Tim Berners-Lee','Bill Gates','Alan Turing'],1,'Tim Berners-Lee propose le World Wide Web au CERN en 1989.'),
Q('T06','tech','hard','Que signifie le « S » de HTTPS ?',['Simple','Secure','System','Shared'],1,'HTTPS est la version sécurisée de HTTP via chiffrement TLS.'),
Q('T07','tech','expert','Qui a créé JavaScript en 1995 ?',['James Gosling','Brendan Eich','Guido van Rossum','Bjarne Stroustrup'],1,'Brendan Eich crée JavaScript chez Netscape en 1995.'),
Q('T08','tech','expert','Quel type de mémoire perd généralement son contenu quand l’alimentation est coupée ?',['ROM','RAM','SSD','Blu-ray'],1,'La RAM classique est une mémoire volatile.'),

Q('SP01','sport','easy','Combien de joueurs une équipe de football aligne-t-elle normalement sur le terrain au coup d’envoi ?',['9','10','11','12'],2,'Une équipe commence normalement avec 11 joueurs.'),
Q('SP02','sport','easy','Quelle couleur porte le leader du classement général du Tour de France ?',['Verte','Jaune','Blanche','Rouge'],1,'Le maillot jaune distingue le leader du classement général.'),
Q('SP03','sport','normal','Combien de joueurs une équipe de rugby à XV aligne-t-elle sur le terrain ?',['11','13','15','16'],2,'Le rugby à XV se joue à 15 joueurs par équipe.'),
Q('SP04','sport','normal','Combien y a-t-il d’anneaux sur le symbole olympique ?',['4','5','6','7'],1,'Le symbole olympique est composé de cinq anneaux entrelacés.'),
Q('SP05','sport','hard','À quelle hauteur réglementaire se trouve l’arceau de basket ?',['2,75 m','3,05 m','3,25 m','3,50 m'],1,'Le panier est à 10 pieds, soit environ 3,05 m.'),
Q('SP06','sport','hard','Combien de tournois composent le Grand Chelem de tennis ?',['3','4','5','6'],1,'Open d’Australie, Roland-Garros, Wimbledon et US Open.'),
Q('SP07','sport','expert','Quelle est la distance officielle d’un marathon ?',['40 km','41,195 km','42,195 km','43 km'],2,'Le marathon mesure officiellement 42,195 km.'),
Q('SP08','sport','expert','Quel drapeau indique traditionnellement la fin d’une course automobile ?',['Rouge','Noir','À damier','Bleu'],2,'Le drapeau à damier marque l’arrivée.'),

Q('R01','retro','easy','Quel système d’exploitation Microsoft porte le nom d’une année ?',['Windows 95','Windows XP','Windows Vista','Windows NT'],0,'Windows 95 est lancé en 1995.'),
Q('R02','retro','easy','Quel téléphone Nokia lancé en 2000 est devenu un symbole des années 2000 ?',['3210','3310','6600','N95'],1,'Le Nokia 3310 est lancé en 2000.'),
Q('R03','retro','normal','Dans quel pays le Tamagotchi est-il lancé à l’origine en 1996 ?',['États-Unis','Japon','France','Corée du Sud'],1,'Bandai lance le Tamagotchi au Japon en 1996.'),
Q('R04','retro','normal','Quelle console Sega est lancée en Europe en 1999 ?',['Saturn','Mega Drive','Dreamcast','Game Gear'],2,'La Dreamcast arrive en Europe en octobre 1999.'),
Q('R05','retro','hard','En quelle année MSN Messenger est-il lancé ?',['1997','1998','1999','2001'],2,'MSN Messenger est lancé par Microsoft en 1999.'),
Q('R06','retro','hard','En quelle année le premier iPod est-il présenté ?',['1999','2000','2001','2003'],2,'Apple présente le premier iPod en octobre 2001.'),
Q('R07','retro','expert','Dans quel pays le DVD vidéo est-il d’abord commercialisé en 1996 ?',['Japon','France','Canada','Australie'],0,'Les premiers lecteurs et disques DVD commerciaux apparaissent au Japon en 1996.'),
Q('R08','retro','expert','Quelle console portable Nintendo est sortie en Europe en 1990 ?',['Game Boy','Game Gear','Game Boy Color','Atari Lynx'],0,'La Game Boy arrive en Europe en 1990.'),

Q('I01','insolite','easy','Combien de cœurs possède une pieuvre ?',['1','2','3','4'],2,'Une pieuvre possède trois cœurs.'),
Q('I02','insolite','easy','De quelle couleur est la peau d’un ours polaire sous sa fourrure ?',['Blanche','Rose','Noire','Grise'],2,'La peau de l’ours polaire est noire ; ses poils paraissent blancs.'),
Q('I03','insolite','normal','Quel animal produit des excréments souvent décrits comme cubiques ?',['Koala','Wombat','Panda','Lémurien'],1,'Le wombat est célèbre pour ses crottes de forme cubique.'),
Q('I04','insolite','normal','Pourquoi les flamants roses sont-ils roses ?',['À cause du sel','À cause de pigments caroténoïdes dans leur alimentation','À cause du soleil','Ils naissent rose vif'],1,'Les caroténoïdes présents dans leur alimentation colorent leur plumage.'),
Q('I05','insolite','hard','Sur quelle planète une rotation sur elle-même dure-t-elle plus longtemps que son année autour du Soleil ?',['Mars','Vénus','Jupiter','Mercure'],1,'Vénus tourne sur elle-même très lentement : son jour sidéral dépasse son année.'),
Q('I06','insolite','hard','Botaniquement, lequel de ces fruits est une baie ?',['Fraise','Banane','Framboise','Cerise'],1,'La banane est botaniquement une baie, contrairement à la fraise.'),
Q('I07','insolite','expert','Combien de vertèbres cervicales possède généralement une girafe ?',['5','7','9','12'],1,'Comme la plupart des mammifères, la girafe possède sept vertèbres cervicales, très allongées.'),
Q('I08','insolite','expert','Quel mammifère est capable de vol actif soutenu ?',['Écureuil volant','Chauve-souris','Colugo','Phalanger volant'],1,'Les chauves-souris sont les seuls mammifères capables de véritable vol actif soutenu.')
];
