// Quiz Libre V3 — 50 nouvelles questions (partie B)
QUESTIONS.push(
QV3("M09","musique","easy","Quel artiste est surnommé le « King of Pop » ?",["Prince","Michael Jackson","Elvis Presley","George Michael"],1,"Michael Jackson est couramment surnommé le King of Pop.",["Jackson"]),
QV3("M10","musique","easy","Combien de touches possède généralement un piano moderne standard ?",["61","76","88","96"],2,"Un piano acoustique moderne standard possède généralement 88 touches."),
QV3("M11","musique","easy","Quel groupe interprète « Bohemian Rhapsody » ?",["Queen","Muse","The Who","U2"],0,"Bohemian Rhapsody est un morceau de Queen."),
QV3("M12","musique","normal","Qui interprète « Like a Virgin » ?",["Madonna","Cyndi Lauper","Cher","Whitney Houston"],0,"Like a Virgin est l’un des grands succès de Madonna."),
QV3("M13","musique","normal","Quel duo français interprète « One More Time » ?",["Air","Justice","Daft Punk","Cassius"],2,"One More Time est un titre de Daft Punk."),
QV3("M14","musique","normal","De quel instrument Yo-Yo Ma est-il un virtuose ?",["Violon","Violoncelle","Piano","Flûte"],1,"Yo-Yo Ma est un violoncelliste de renommée internationale.",["Cello"]),
QV3("M15","musique","hard","Quel compositeur baroque est l’auteur des « Quatre Saisons » ?",["Bach","Vivaldi","Haendel","Telemann"],1,"Antonio Vivaldi compose Les Quatre Saisons.",["Antonio Vivaldi"]),
QV3("M16","musique","hard","Quel groupe a sorti l’album « The Dark Side of the Moon » ?",["Pink Floyd","Led Zeppelin","Genesis","Deep Purple"],0,"Pink Floyd publie The Dark Side of the Moon en 1973."),
QV3("M17","musique","expert","Quel est le nom de scène de David Robert Jones ?",["David Bowie","Elton John","Sting","Morrissey"],0,"David Robert Jones adopte le nom de scène David Bowie.",["Bowie"]),
QV3("M18","musique","expert","Quel trompettiste de jazz est au centre de l’album « Kind of Blue » ?",["Louis Armstrong","Miles Davis","Chet Baker","Dizzy Gillespie"],1,"Miles Davis dirige les sessions de Kind of Blue.",["Davis"]),
QV3("T09","tech","easy","Que signifie l’acronyme USB ?",["Universal Serial Bus","Unified System Base","User Service Bridge","Universal Signal Band"],0,"USB signifie Universal Serial Bus."),
QV3("T10","tech","easy","Que signifie CPU en informatique ?",["Central Processing Unit","Computer Personal Utility","Core Program User","Central Peripheral Unit"],0,"CPU signifie Central Processing Unit.",["Processeur","Unité centrale de traitement","Unite centrale de traitement"]),
QV3("T11","tech","easy","Que signifie PNG dans le nom du format d’image ?",["Portable Network Graphics","Personal Numeric Graphic","Pixel Network Group","Public Network Grid"],0,"PNG signifie Portable Network Graphics."),
QV3("T12","tech","normal","Comment s’appelait le premier navigateur web créé par Tim Berners-Lee ?",["Mosaic","WorldWideWeb","Netscape Navigator","Lynx"],1,"Le premier navigateur de Tim Berners-Lee s’appelait WorldWideWeb, puis Nexus.",["Nexus","World Wide Web"]),
QV3("T13","tech","normal","Que signifie SQL ?",["Simple Query Link","Structured Query Language","System Queue Logic","Standard Quick Language"],1,"SQL signifie Structured Query Language."),
QV3("T14","tech","normal","Que signifie IP dans « adresse IP » ?",["Internet Protocol","Internal Port","Information Packet","Interface Process"],0,"IP signifie Internet Protocol."),
QV3("T15","tech","hard","Qui a créé le système de gestion de versions Git ?",["Richard Stallman","Linus Torvalds","Ken Thompson","Guido van Rossum"],1,"Linus Torvalds crée Git en 2005.",["Torvalds"]),
QV3("T16","tech","hard","Que signifie TCP ?",["Transfer Control Package","Transmission Control Protocol","Terminal Connection Process","Transport Core Protocol"],1,"TCP signifie Transmission Control Protocol."),
QV3("T17","tech","expert","Combien de bits composent un octet ?",["4","8","16","32"],1,"Un octet contient 8 bits.",["8 bits"]),
QV3("T18","tech","expert","Que signifie SHA dans des noms comme SHA-256 ?",["Secure Hash Algorithm","System Host Access","Sequential Hex Array","Secure Hardware Address"],0,"SHA signifie Secure Hash Algorithm."),
QV3("SP09","sport","easy","Combien de joueurs d’une même équipe sont sur le terrain en basket-ball ?",["4","5","6","7"],1,"Une équipe de basket-ball aligne cinq joueurs sur le terrain."),
QV3("SP10","sport","easy","Au tennis, quel score vient après 30 dans un jeu classique ?",["35","40","45","50"],1,"Le décompte classique passe de 30 à 40."),
QV3("SP11","sport","easy","Quelle est la longueur d’un bassin olympique de natation ?",["25 m","33 m","50 m","100 m"],2,"Un bassin olympique mesure 50 mètres."),
QV3("SP12","sport","normal","Combien de joueurs une équipe de volley-ball aligne-t-elle sur le terrain ?",["5","6","7","8"],1,"Une équipe de volley-ball compte six joueurs sur le terrain."),
QV3("SP13","sport","normal","À quelle distance du but se trouve le point de penalty au football ?",["9 m","10 m","11 m","12 m"],2,"Le point de penalty est situé à 11 mètres de la ligne de but.",["11 mètres","11 metres"]),
QV3("SP14","sport","normal","Dans quel territoire se dispute le célèbre Grand Prix automobile de Monaco ?",["France","Italie","Monaco","Suisse"],2,"Le Grand Prix se déroule dans les rues de la principauté de Monaco."),
QV3("SP15","sport","hard","Combien de manches réglementaires compte normalement un match de baseball professionnel ?",["7","8","9","10"],2,"Un match réglementaire de baseball se joue normalement en neuf manches.",["9 manches"]),
QV3("SP16","sport","hard","Combien d’épreuves composent un décathlon ?",["8","9","10","12"],2,"Le décathlon regroupe dix épreuves.",["10 épreuves","10 epreuves"]),
QV3("SP17","sport","expert","Quel est le poids réglementaire du poids masculin senior au lancer du poids ?",["5 kg","6 kg","7,26 kg","8 kg"],2,"Le poids masculin senior pèse 7,26 kg.",["7.26 kg","7,26","7.26"]),
QV3("SP18","sport","expert","À combien de points se joue normalement une manche de tennis de table moderne ?",["11","15","21","25"],0,"Une manche se joue normalement en 11 points, avec deux points d’écart requis.",["11 points"]),
QV3("R09","retro","easy","En quelle année Windows 95 est-il commercialisé ?",["1993","1995","1997","1999"],1,"Windows 95 est lancé en août 1995."),
QV3("R10","retro","easy","Quel jouet électronique à fourrure devient un phénomène mondial à la fin des années 1990 ?",["Tamagotchi","Furby","Bop It","Poo-Chi"],1,"Le Furby est lancé en 1998 et devient un énorme succès."),
QV3("R11","retro","easy","Quel Pokémon jaune devient la mascotte emblématique de la franchise ?",["Psykokwak","Pikachu","Évoli","Rondoudou"],1,"Pikachu est la mascotte la plus emblématique de Pokémon."),
QV3("R12","retro","normal","En quelle année le service Napster est-il lancé ?",["1997","1999","2001","2003"],1,"Napster est lancé en 1999."),
QV3("R13","retro","normal","Quel jeu était particulièrement associé au Nokia 3310 ?",["Tetris","Snake II","Pac-Man","Breakout"],1,"Le Nokia 3310 embarquait notamment Snake II.",["Snake"]),
QV3("R14","retro","normal","En quelle année la PlayStation 2 sort-elle en Europe ?",["1999","2000","2001","2002"],1,"La PlayStation 2 arrive en Europe en novembre 2000.",["2000"]),
QV3("R15","retro","hard","En quelle année la Sega Saturn est-elle commercialisée en Europe ?",["1994","1995","1996","1997"],1,"La Sega Saturn arrive en Europe en juillet 1995."),
QV3("R16","retro","hard","Quelle console portable Sony arrive en Europe en 2005 ?",["PS Vita","PSP","PocketStation","PS one Portable"],1,"La PlayStation Portable, ou PSP, est lancée en Europe en 2005.",["PlayStation Portable"]),
QV3("R17","retro","expert","Quelle entreprise israélienne a créé ICQ en 1996 ?",["Mirabilis","Netscape","RealNetworks","Nullsoft"],0,"ICQ est créé par la société israélienne Mirabilis."),
QV3("R18","retro","expert","Quel navigateur web Microsoft lance-t-il en 1995 ?",["Edge","Internet Explorer","Mosaic","Opera"],1,"Internet Explorer 1.0 apparaît en 1995.",["IE","IE 1","Internet Explorer 1"]),
QV3("I09","insolite","easy","De quelle couleur est le sang des pieuvres ?",["Rouge","Bleu","Vert","Jaune"],1,"Le sang des pieuvres paraît bleu car il utilise de l’hémocyanine riche en cuivre."),
QV3("I10","insolite","easy","Quel est le plus grand animal connu vivant actuellement ?",["Éléphant d’Afrique","Baleine bleue","Requin-baleine","Calmar géant"],1,"La baleine bleue est le plus grand animal connu.",["Baleine bleue"]),
QV3("I11","insolite","easy","Quel est le plus grand oiseau vivant, incapable de voler ?",["Émeu","Autruche","Casoar","Albatros"],1,"L’autruche est le plus grand oiseau vivant.",["Autruche"]),
QV3("I12","insolite","normal","Le bananier est botaniquement plutôt…",["Un arbre","Une herbe géante","Un palmier","Un arbuste ligneux"],1,"Le bananier est une grande plante herbacée, pas un arbre au sens botanique.",["Une herbe","Herbe géante","Herbe geante"]),
QV3("I13","insolite","normal","De quoi est principalement constitué le squelette des requins ?",["Os","Cartilage","Kératine","Calcaire"],1,"Le squelette des requins est cartilagineux.",["Cartilage"]),
QV3("I14","insolite","normal","Quel animal possède des empreintes digitales étonnamment proches de celles des humains ?",["Koala","Paresseux","Panda","Loutre"],0,"Les koalas possèdent des empreintes digitales très proches visuellement de celles des humains.",["Koala"]),
QV3("I15","insolite","hard","Quel amphibien nord-américain peut survivre à la congélation partielle de son corps en hiver ?",["Crapaud buffle","Grenouille des bois","Axolotl","Salamandre géante"],1,"La grenouille des bois peut tolérer qu’une partie importante de son corps gèle.",["Grenouille des bois","Wood frog"]),
QV3("I16","insolite","hard","Quel métal est liquide à température ambiante autour de 20 °C ?",["Fer","Mercure","Aluminium","Cuivre"],1,"Le mercure est liquide à température ambiante usuelle."),
QV3("I17","insolite","expert","Quel amphibien est célèbre pour sa capacité à régénérer des membres entiers ?",["Axolotl","Dendrobate","Triton crêté","Crapaud commun"],0,"L’axolotl possède des capacités de régénération remarquables."),
QV3("I18","insolite","expert","Quel mammifère pond des œufs et dont le mâle possède un aiguillon venimeux à la patte arrière ?",["Échidné","Ornithorynque","Pangolin","Wombat"],1,"L’ornithorynque pond des œufs et le mâle possède un aiguillon venimeux sur les pattes arrière.",["Ornithorynque"]),
);