const fs=require('fs');
const path=require('path');
const assert=require('assert');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const v4css=fs.readFileSync(path.join(root,'v4.css'),'utf8');
const requiredIds=['homeScreen','gameScreen','resultScreen','homeBtn','statAnswered','statRate','statBest','categoryPanel','categoryGrid','difficulty','count','answerMode','startBtn','seenInfo','resetBtn','gameCounter','progress','scoreMini','categoryBadge','answerTypeBadge','difficultyBadge','questionText','answers','freeAnswerWrap','freeAnswerInput','freeAnswerBtn','feedback','nextBtn','streak','bigScore','resultPercent','resultStreak','resultPoints','resultIcon','resultMessage','replayBtn','backBtn','toast'];
for(const id of requiredIds) assert.ok(html.includes(`id="${id}"`),`ID DOM manquant: ${id}`);
const scripts=[...html.matchAll(/<script src="([^"]+)"><\/script>/g)].map(m=>m[1]);
const expected=['questions/index.js','questions/histoire.js','questions/geographie.js','questions/sciences.js','questions/cinema.js','questions/jeux.js','questions/musique.js','questions/tech.js','questions/sport.js','questions/retro.js','questions/insolite.js','answer-utils.js','app.js'];
assert.deepStrictEqual(scripts,expected,'Ordre de chargement des scripts incorrect');
const styles=[...html.matchAll(/<link rel="stylesheet" href="([^"]+)"/g)].map(m=>m[1]);
assert.deepStrictEqual(styles,['styles.css','v3.css','v4.css'],'Ordre CSS V4 incorrect');
assert.ok(v4css.includes("url('assets/warehouse-neon.jpg')"),'Le décor approuvé doit être un asset séparé');
assert.ok(!v4css.includes('data:image/'),'Le CSS source ne doit pas ré-incruster une maquette UI en data URI');
assert.ok(html.includes('500 QUESTIONS'),'L’accueil doit annoncer 500 questions');
assert.ok(!html.includes('180 QUESTIONS'),'L’accueil ne doit plus annoncer 180 questions');
assert.ok(app.includes('QUESTIONS.length===500'),'Le self-test doit exiger 500 questions');
console.log('PASS wiring-v4: DOM, décor vierge, CSS V4, scripts packs et self-test 500');
