QUESTIONS.push(
  Q("C01","cinema","easy","Qui réalise « Jurassic Park » sorti en 1993 ?",["James Cameron","Steven Spielberg","Ridley Scott","George Lucas"],1,"Steven Spielberg réalise Jurassic Park.",["Spielberg"]),
  Q("C02","cinema","easy","Comment s’appelle le professeur de chimie de « Breaking Bad » ?",["Jesse Pinkman","Walter White","Saul Goodman","Gus Fring"],1,"Walter White devient le personnage central de la série.",[]),
  Q("C03","cinema","normal","Quelle voiture sert de machine à voyager dans le temps dans « Retour vers le futur » ?",["Ford Mustang","DeLorean DMC-12","Pontiac Firebird","Chevrolet Corvette"],1,"Doc transforme une DeLorean DMC-12 en machine temporelle.",[]),
  Q("C04","cinema","normal","Dans quelle ville fictive vivent les héros de « Stranger Things » ?",["Sunnydale","Hawkins","Riverdale","Twin Peaks"],1,"La série se déroule principalement à Hawkins, dans l’Indiana.",[]),
  Q("C05","cinema","hard","Qui a réalisé « Le Parrain » ?",["Martin Scorsese","Francis Ford Coppola","Brian De Palma","Sergio Leone"],1,"Francis Ford Coppola réalise Le Parrain, sorti en 1972.",["Coppola"]),
  Q("C06","cinema","hard","Qui a écrit le roman « Le Seigneur des anneaux » ?",["C. S. Lewis","J. R. R. Tolkien","George R. R. Martin","Terry Pratchett"],1,"J. R. R. Tolkien est l’auteur du Seigneur des anneaux.",["Tolkien"]),
  Q("C07","cinema","expert","En quelle année le premier « Star Wars » sorti au cinéma, devenu l’Épisode IV, est-il lancé ?",["1975","1977","1979","1981"],1,"Star Wars sort pour la première fois en 1977.",[]),
  Q("C08","cinema","expert","Qui a réalisé la trilogie originale de « Matrix » avec Lilly Wachowski ?",["Lana Wachowski","Kathryn Bigelow","Patty Jenkins","Sofia Coppola"],0,"Lana et Lilly Wachowski ont écrit et réalisé la trilogie originale.",[]),
  Q("C09","cinema","easy","Quel acteur incarne Harry Potter dans la saga cinématographique principale ?",["Rupert Grint","Daniel Radcliffe","Tom Felton","Robert Pattinson"],1,"Daniel Radcliffe incarne Harry Potter dans les huit films principaux.",["Radcliffe"]),
  Q("C10","cinema","easy","Quel aventurier de cinéma porte un fedora et utilise souvent un fouet ?",["Rocky Balboa","Indiana Jones","John McClane","Ethan Hunt"],1,"Indiana Jones est l’archéologue-aventurier créé par George Lucas.",["Indy"]),
  Q("C11","cinema","easy","Qui réalise « Titanic » sorti en 1997 ?",["James Cameron","Steven Spielberg","Ridley Scott","Peter Jackson"],0,"James Cameron réalise Titanic.",["Cameron"]),
  Q("C12","cinema","normal","Quel acteur incarne Neo dans la saga « Matrix » ?",["Keanu Reeves","Brad Pitt","Christian Bale","Matt Damon"],0,"Keanu Reeves joue Neo dans Matrix.",["Reeves"]),
  Q("C13","cinema","normal","Combien de maisons principales compte Poudlard dans « Harry Potter » ?",["3","4","5","6"],1,"Poudlard compte Gryffondor, Serpentard, Serdaigle et Poufsouffle.",[]),
  Q("C14","cinema","normal","Quelle ville fictive est principalement associée à Batman ?",["Metropolis","Gotham City","Central City","Star City"],1,"Batman protège principalement Gotham City.",["Gotham"]),
  Q("C15","cinema","hard","Qui a réalisé « Pulp Fiction » ?",["David Fincher","Quentin Tarantino","Martin Scorsese","Joel Coen"],1,"Quentin Tarantino réalise Pulp Fiction, sorti en 1994.",["Tarantino"]),
  Q("C16","cinema","hard","De quel pays vient le film « Parasite » de Bong Joon-ho ?",["Japon","Corée du Sud","Chine","Thaïlande"],1,"Parasite est un film sud-coréen.",["Coree du Sud","Corée"]),
  Q("C17","cinema","expert","Quel compositeur signe les thèmes musicaux les plus célèbres de « Star Wars » ?",["Hans Zimmer","John Williams","Ennio Morricone","Howard Shore"],1,"John Williams compose la musique emblématique de Star Wars.",["Williams"]),
  Q("C18","cinema","expert","Qui a réalisé « 2001 : l’Odyssée de l’espace » ?",["Stanley Kubrick","Orson Welles","Alfred Hitchcock","David Lean"],0,"Stanley Kubrick réalise 2001 : l’Odyssée de l’espace.",["Kubrick"]),
  Q("C19","cinema","easy","Qui a réalisé « Titanic » ?",["Federico Fellini","Ingmar Bergman","James Cameron","Steven Spielberg"],2,"James Cameron a réalisé Titanic.",["Cameron"]),
  Q("C20","cinema","easy","Qui a réalisé « Reservoir Dogs » ?",["Alfonso Cuarón","James Cameron","Quentin Tarantino","Federico Fellini"],2,"Quentin Tarantino a réalisé Reservoir Dogs.",["Tarantino"]),
  Q("C21","cinema","easy","Qui a réalisé « Inception » ?",["David Lynch","Stanley Kubrick","Terry Gilliam","Christopher Nolan"],3,"Christopher Nolan a réalisé Inception.",["Nolan"]),
  Q("C22","cinema","easy","Qui a réalisé « E.T. l'extra-terrestre » ?",["Park Chan-wook","Steven Spielberg","Terry Gilliam","Andreï Tarkovski"],1,"Steven Spielberg a réalisé E.T.",["Spielberg"]),
  Q("C23","cinema","easy","Qui a réalisé « Avatar » sorti en 2009 ?",["Ridley Scott","Park Chan-wook","James Cameron","Terry Gilliam"],2,"James Cameron a réalisé Avatar.",["Cameron"]),
  Q("C24","cinema","easy","Qui a réalisé « Le Fabuleux Destin d'Amélie Poulain » ?",["Jean-Pierre Jeunet","Terry Gilliam","Christopher Nolan","Andreï Tarkovski"],0,"Jean-Pierre Jeunet a réalisé le film.",["Jeunet"]),
  Q("C25","cinema","easy","Qui a réalisé « Fight Club » ?",["Mathieu Kassovitz","Federico Fellini","David Fincher","Michael Mann"],2,"David Fincher a réalisé Fight Club.",["Fincher"]),
  Q("C26","cinema","normal","Qui a réalisé « Alien, le huitième passager » ?",["Francis Ford Coppola","Bong Joon-ho","Hayao Miyazaki","Ridley Scott"],3,"Ridley Scott a réalisé Alien.",["Ridley Scott"]),
  Q("C27","cinema","normal","Qui a réalisé « Les Affranchis » (Goodfellas) ?",["Martin Scorsese","Federico Fellini","Nicolas Winding Refn","Quentin Tarantino"],0,"Martin Scorsese a réalisé Les Affranchis.",["Scorsese"]),
  Q("C28","cinema","normal","Qui a réalisé « Le Voyage de Chihiro » ?",["Hayao Miyazaki","Federico Fellini","Chantal Akerman","David Lynch"],0,"Hayao Miyazaki a réalisé Le Voyage de Chihiro.",["Miyazaki"]),
  Q("C29","cinema","normal","Qui a réalisé « Parasite » ?",["Bong Joon-ho","James Cameron","David Fincher","Terry Gilliam"],0,"Bong Joon-ho a réalisé Parasite.",["Bong Joon Ho"]),
  Q("C30","cinema","normal","Qui a réalisé « Gladiator » sorti en 2000 ?",["Ridley Scott","Quentin Tarantino","Michael Mann","Ingmar Bergman"],0,"Ridley Scott a réalisé Gladiator.",[]),
  Q("C31","cinema","normal","Qui a réalisé « Shining » ?",["Hayao Miyazaki","David Fincher","Chantal Akerman","Stanley Kubrick"],3,"Stanley Kubrick a réalisé Shining.",["Kubrick"]),
  Q("C32","cinema","normal","Qui a réalisé « Interstellar » ?",["Peter Weir","Damien Chazelle","Christopher Nolan","Guillermo del Toro"],2,"Christopher Nolan a réalisé Interstellar.",[]),
  Q("C33","cinema","normal","Qui a réalisé « La Haine » ?",["Francis Ford Coppola","Alfonso Cuarón","Mathieu Kassovitz","Chantal Akerman"],2,"Mathieu Kassovitz a réalisé La Haine.",["Kassovitz"]),
  Q("C34","cinema","normal","Qui a réalisé « The Truman Show » ?",["Quentin Tarantino","Bong Joon-ho","Peter Weir","Andreï Tarkovski"],2,"Peter Weir a réalisé The Truman Show.",[]),
  Q("C35","cinema","hard","Qui a réalisé « Blade Runner » sorti en 1982 ?",["Michael Mann","Christopher Nolan","Ridley Scott","Chantal Akerman"],2,"Ridley Scott a réalisé Blade Runner.",[]),
  Q("C36","cinema","hard","Qui a réalisé « Mulholland Drive » ?",["Nicolas Winding Refn","Damien Chazelle","David Lynch","Bong Joon-ho"],2,"David Lynch a réalisé Mulholland Drive.",["Lynch"]),
  Q("C37","cinema","hard","Qui a réalisé « Old Boy » sorti en 2003 ?",["Bong Joon-ho","Terry Gilliam","Park Chan-wook","Guillermo del Toro"],2,"Park Chan-wook a réalisé Old Boy.",["Park Chan Wook"]),
  Q("C38","cinema","hard","Qui a réalisé « Le Labyrinthe de Pan » ?",["Andreï Tarkovski","Guillermo del Toro","Hayao Miyazaki","Steven Spielberg"],1,"Guillermo del Toro a réalisé Le Labyrinthe de Pan.",["Del Toro"]),
  Q("C39","cinema","hard","Qui a réalisé « Memories of Murder » ?",["Ridley Scott","Bong Joon-ho","Akira Kurosawa","David Fincher"],1,"Bong Joon-ho a réalisé Memories of Murder.",[]),
  Q("C40","cinema","hard","Qui a réalisé « Heat » sorti en 1995 ?",["Michael Mann","Bong Joon-ho","Stanley Kubrick","Peter Weir"],0,"Michael Mann a réalisé Heat.",[]),
  Q("C41","cinema","hard","Qui a réalisé « Brazil » sorti en 1985 ?",["Christopher Nolan","Terry Gilliam","Park Chan-wook","Akira Kurosawa"],1,"Terry Gilliam a réalisé Brazil.",[]),
  Q("C42","cinema","hard","Qui a réalisé « Les Fils de l'homme » (Children of Men) ?",["Bong Joon-ho","Martin Scorsese","Hayao Miyazaki","Alfonso Cuarón"],3,"Alfonso Cuarón a réalisé Les Fils de l'homme.",["Alfonso Cuaron","Cuaron"]),
  Q("C43","cinema","hard","Qui a réalisé « Drive » sorti en 2011 ?",["Ridley Scott","Michael Mann","Nicolas Winding Refn","Christopher Nolan"],2,"Nicolas Winding Refn a réalisé Drive.",["Refn"]),
  Q("C44","cinema","hard","Qui a réalisé « Whiplash » ?",["Damien Chazelle","David Fincher","Chantal Akerman","Nicolas Winding Refn"],0,"Damien Chazelle a réalisé Whiplash.",["Chazelle"]),
  Q("C45","cinema","expert","Qui a réalisé « Stalker » sorti en 1979 ?",["Christopher Nolan","Damien Chazelle","Nicolas Winding Refn","Andreï Tarkovski"],3,"Andreï Tarkovski a réalisé Stalker.",["Andrei Tarkovski","Tarkovski","Tarkovsky"]),
  Q("C46","cinema","expert","Qui a réalisé « Persona » sorti en 1966 ?",["Nicolas Winding Refn","Andreï Tarkovski","Ingmar Bergman","Damien Chazelle"],2,"Ingmar Bergman a réalisé Persona.",["Bergman"]),
  Q("C47","cinema","expert","Qui a réalisé « Huit et demi » (8½) ?",["Ridley Scott","Steven Spielberg","Nicolas Winding Refn","Federico Fellini"],3,"Federico Fellini a réalisé 8½.",["Fellini"]),
  Q("C48","cinema","expert","Qui a réalisé « Rashōmon » ?",["Michael Mann","Akira Kurosawa","Quentin Tarantino","Steven Spielberg"],1,"Akira Kurosawa a réalisé Rashōmon.",["Kurosawa"]),
  Q("C49","cinema","expert","Qui a réalisé « Conversation secrète » (The Conversation) ?",["Jean-Pierre Jeunet","Francis Ford Coppola","Chantal Akerman","Andreï Tarkovski"],1,"Francis Ford Coppola a réalisé The Conversation.",["Coppola"]),
  Q("C50","cinema","expert","Qui a réalisé « Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles » ?",["David Fincher","Chantal Akerman","Guillermo del Toro","Hayao Miyazaki"],1,"Chantal Akerman a réalisé Jeanne Dielman.",["Akerman"])
);
