QUESTIONS.push(
  Q("G01","geographie","easy","Quelle est la capitale de l’Australie ?",["Sydney","Melbourne","Canberra","Perth"],2,"Canberra est la capitale fédérale de l’Australie.",[]),
  Q("G02","geographie","easy","Quel est le plus grand pays du monde par superficie ?",["Canada","Chine","États-Unis","Russie"],3,"La Russie est le plus vaste État du monde.",[]),
  Q("G03","geographie","normal","Dans quel pays se trouve le Kilimandjaro ?",["Kenya","Tanzanie","Éthiopie","Ouganda"],1,"Le Kilimandjaro se situe dans le nord-est de la Tanzanie.",[]),
  Q("G04","geographie","normal","Dans quel océan se trouve Madagascar ?",["Atlantique","Pacifique","Indien","Arctique"],2,"Madagascar est une île de l’océan Indien.",[]),
  Q("G05","geographie","hard","Dans quelle mer se jette le Danube ?",["Mer Baltique","Mer Noire","Mer Adriatique","Mer Égée"],1,"Le Danube forme un vaste delta avant de se jeter dans la mer Noire.",[]),
  Q("G06","geographie","hard","Quel détroit sépare principalement l’Espagne du Maroc ?",["Béring","Ormuz","Gibraltar","Malacca"],2,"Le détroit de Gibraltar relie Atlantique et Méditerranée.",[]),
  Q("G07","geographie","expert","Dans quel pays se trouve le lac Baïkal ?",["Mongolie","Russie","Kazakhstan","Finlande"],1,"Le lac Baïkal se trouve en Sibérie, en Russie.",[]),
  Q("G08","geographie","expert","Quel est le plus grand désert du monde si l’on inclut les déserts froids ?",["Sahara","Gobi","Antarctique","Arabie"],2,"L’Antarctique est un désert polaire et le plus vaste désert terrestre.",[]),
  Q("G09","geographie","easy","Quelle est la capitale du Canada ?",["Toronto","Vancouver","Ottawa","Montréal"],2,"Ottawa est la capitale fédérale du Canada.",[]),
  Q("G10","geographie","easy","Quel est le plus vaste océan de la planète ?",["Atlantique","Indien","Pacifique","Arctique"],2,"L’océan Pacifique est le plus vaste océan terrestre.",["Ocean Pacifique"]),
  Q("G11","geographie","easy","Quel fleuve traverse Paris ?",["Loire","Seine","Rhône","Garonne"],1,"La Seine traverse Paris avant de rejoindre la Manche.",[]),
  Q("G12","geographie","normal","Quelle est la capitale de la Nouvelle-Zélande ?",["Auckland","Christchurch","Wellington","Hamilton"],2,"Wellington est la capitale de la Nouvelle-Zélande.",[]),
  Q("G13","geographie","normal","Quelle chaîne de montagnes sépare en grande partie la France et l’Espagne ?",["Les Alpes","Les Pyrénées","Les Carpates","Les Apennins"],1,"Les Pyrénées forment une frontière naturelle majeure entre la France et l’Espagne.",["Pyrenees"]),
  Q("G14","geographie","normal","Dans quel pays se trouve le Machu Picchu ?",["Bolivie","Pérou","Équateur","Chili"],1,"Le Machu Picchu se trouve au Pérou.",["Perou"]),
  Q("G15","geographie","hard","Quelle fosse océanique abrite le point le plus profond connu des océans ?",["Fosse de Java","Fosse des Mariannes","Fosse du Pérou-Chili","Fosse des Tonga"],1,"La fosse des Mariannes contient le Challenger Deep, le point océanique connu le plus profond.",["Mariannes","Fosse des Mariannes"]),
  Q("G16","geographie","hard","Quel pays est entièrement enclavé à l’intérieur de l’Afrique du Sud ?",["Eswatini","Lesotho","Botswana","Namibie"],1,"Le Lesotho est entièrement entouré par l’Afrique du Sud.",[]),
  Q("G17","geographie","expert","Dans quel pays se trouve le Salar d’Uyuni, immense désert de sel ?",["Pérou","Bolivie","Argentine","Chili"],1,"Le Salar d’Uyuni se trouve en Bolivie.",["Bolivie"]),
  Q("G18","geographie","expert","Quel fleuve traverse Budapest ?",["Rhin","Danube","Vistule","Dniepr"],1,"Budapest s’étend sur les deux rives du Danube.",[]),
  Q("G19","geographie","easy","Quelle est la capitale de la Suède ?",["Brasília","Stockholm","Tokyo","Nairobi"],1,"Stockholm est la capitale de la Suède.",[]),
  Q("G20","geographie","easy","Quelle est la capitale du Brésil ?",["Séoul","Brasília","Ankara","Oslo"],1,"Brasília est la capitale du Brésil depuis 1960.",["Brasilia"]),
  Q("G21","geographie","easy","Quelle est la capitale de la Turquie ?",["Berne","Brasília","Séoul","Ankara"],3,"Ankara est la capitale de la Turquie.",[]),
  Q("G22","geographie","easy","Quelle est la capitale de la Suisse ?",["Oslo","Berne","Stockholm","Lima"],1,"Berne est la ville fédérale de la Suisse.",[]),
  Q("G23","geographie","easy","Quelle est la capitale du Maroc ?",["Lisbonne","Brasília","Rabat","Berne"],2,"Rabat est la capitale du Maroc.",[]),
  Q("G24","geographie","easy","Quelle est la capitale de la Corée du Sud ?",["Séoul","Nairobi","Helsinki","Rabat"],0,"Séoul est la capitale de la Corée du Sud.",["Seoul"]),
  Q("G25","geographie","easy","Quelle est la capitale du Japon ?",["Tokyo","Rabat","Hanoï","Buenos Aires"],0,"Tokyo est la capitale du Japon.",[]),
  Q("G26","geographie","normal","Quelle est la capitale de l'Argentine ?",["Berne","Hanoï","Séoul","Buenos Aires"],3,"Buenos Aires est la capitale de l'Argentine.",[]),
  Q("G27","geographie","normal","Quelle est la capitale du Viêt Nam ?",["Lisbonne","Rabat","Hanoï","Ankara"],2,"Hanoï est la capitale du Viêt Nam.",["Hanoi"]),
  Q("G28","geographie","normal","Quelle est la capitale de la Norvège ?",["Hanoï","Tokyo","Buenos Aires","Oslo"],3,"Oslo est la capitale de la Norvège.",[]),
  Q("G29","geographie","normal","Quelle est la capitale de la Finlande ?",["Brasília","Rabat","Oslo","Helsinki"],3,"Helsinki est la capitale de la Finlande.",[]),
  Q("G30","geographie","normal","Quelle est la capitale du Portugal ?",["Lisbonne","Stockholm","Helsinki","Berne"],0,"Lisbonne est la capitale du Portugal.",[]),
  Q("G31","geographie","normal","Quelle est la capitale du Kenya ?",["Nairobi","Stockholm","Rabat","Buenos Aires"],0,"Nairobi est la capitale du Kenya.",[]),
  Q("G32","geographie","normal","Quelle est la capitale du Pérou ?",["Lima","Brasília","Stockholm","Tokyo"],0,"Lima est la capitale du Pérou.",[]),
  Q("G33","geographie","normal","Quelle est la capitale de la Thaïlande ?",["Tokyo","Bangkok","Buenos Aires","Berne"],1,"Bangkok est la capitale de la Thaïlande.",[]),
  Q("G34","geographie","normal","Quelle chaîne de montagnes longe l'ouest de l'Amérique du Sud ?",["Andes","Himalaya","Pamir","Alpes"],0,"La cordillère des Andes longe l'ouest de l'Amérique du Sud.",["Cordillère des Andes"]),
  Q("G35","geographie","hard","Dans quelle mer le Nil se jette-t-il ?",["Mer Noire","Mer du Nord","Méditerranée","Mer Baltique"],2,"Le Nil se jette dans la mer Méditerranée.",["Mer Méditerranée"]),
  Q("G36","geographie","hard","Dans quelle mer le Rhin se jette-t-il ?",["Mer Adriatique","Mer du Nord","Mer Noire","Mer Baltique"],1,"Le Rhin se jette dans la mer du Nord.",[]),
  Q("G37","geographie","hard","Dans quelle région du monde coule principalement le Mékong ?",["Afrique de l’Est","Europe centrale","Asie du Sud-Est","Asie centrale"],2,"Le Mékong traverse plusieurs pays d'Asie du Sud-Est.",[]),
  Q("G38","geographie","hard","Dans quelle chaîne de montagnes se trouve le mont Elbrouz ?",["Pamir","Caucase","Alpes","Andes"],1,"Le mont Elbrouz se situe dans le Caucase.",[]),
  Q("G39","geographie","hard","Dans quel pays se trouve l'Aconcagua ?",["Bolivie","Chili","Lesotho","Argentine"],3,"L'Aconcagua, plus haut sommet des Amériques, se trouve en Argentine.",[]),
  Q("G40","geographie","hard","Dans quel pays se situe principalement le désert d'Atacama ?",["Bolivie","Argentine","Australie","Chili"],3,"Le désert d'Atacama se situe principalement dans le nord du Chili.",[]),
  Q("G41","geographie","hard","Au large de quel pays se trouve la Grande Barrière de corail ?",["Australie","Angola","Chili","Lesotho"],0,"La Grande Barrière de corail longe le nord-est de l'Australie.",[]),
  Q("G42","geographie","hard","Quels trois pays se partagent l'île de Bornéo ?",["Indonésie, Malaisie et Brunei","France, Allemagne et Belgique","Chili, Pérou et Bolivie","Norvège, Suède et Finlande"],0,"Bornéo est partagé entre l'Indonésie, la Malaisie et Brunei.",["Indonésie Malaisie Brunei","Indonesie Malaisie Brunei"]),
  Q("G43","geographie","hard","Quels deux pays se partagent le lac Titicaca ?",["Chili et Argentine","France et Espagne","Pérou et Bolivie","Norvège et Suède"],2,"Le lac Titicaca se trouve à la frontière du Pérou et de la Bolivie.",["Pérou Bolivie","Perou et Bolivie"]),
  Q("G44","geographie","hard","Dans quel océan se trouve la mer des Sargasses ?",["Pacifique Nord","Atlantique Nord","Océan Indien","Atlantique Sud"],1,"La mer des Sargasses se situe dans l'Atlantique Nord.",["Océan Atlantique","Atlantique"]),
  Q("G45","geographie","expert","Quel pays est entièrement enclavé dans l'Afrique du Sud ?",["Australie","Chili","Angola","Lesotho"],3,"Le Lesotho est entièrement entouré par l'Afrique du Sud.",[]),
  Q("G46","geographie","expert","À quel pays appartient l'exclave de Cabinda ?",["Australie","Argentine","Angola","Chili"],2,"Cabinda est une exclave de l'Angola.",[]),
  Q("G47","geographie","expert","Quel détroit relie la mer Rouge au golfe d'Aden ?",["Gibraltar","Bab-el-Mandeb","Ormuz","Béring"],1,"Le détroit de Bab-el-Mandeb relie la mer Rouge au golfe d'Aden.",["Bab el Mandeb"]),
  Q("G48","geographie","expert","Quel massif montagneux d'Asie centrale est parfois surnommé le « toit du monde » ?",["Pamir","Andes","Caucase","Alpes"],0,"Le Pamir est un haut massif d'Asie centrale.",[]),
  Q("G49","geographie","expert","Dans quel pays se trouve le Salar d'Uyuni ?",["Bolivie","Chili","Argentine","Lesotho"],0,"Le Salar d'Uyuni se trouve en Bolivie.",[]),
  Q("G50","geographie","expert","Quel fleuve traverse Londres ?",["Tamise","Danube","Rhin","Mékong"],0,"La Tamise traverse Londres.",[])
);
