QUESTIONS.push(
  Q("J01","jeux","easy","Quel est le nom du héros principal de la série « The Legend of Zelda » ?",["Zelda","Link","Ganondorf","Epona"],1,"Le joueur incarne principalement Link ; Zelda est la princesse.",[]),
  Q("J02","jeux","easy","Quelle entreprise a créé Sonic ?",["Nintendo","Sega","Sony","Atari"],1,"Sonic est la mascotte historique de Sega.",[]),
  Q("J03","jeux","normal","Quel créateur japonais est associé à Mario et The Legend of Zelda ?",["Hideo Kojima","Shigeru Miyamoto","Yu Suzuki","Satoru Iwata"],1,"Shigeru Miyamoto est l’un des créateurs majeurs de Nintendo.",[]),
  Q("J04","jeux","normal","En quelle année le jeu « Doom » original est-il sorti ?",["1989","1991","1993","1996"],2,"Doom d’id Software sort en décembre 1993.",[]),
  Q("J05","jeux","hard","Quel studio/éditeur japonais a créé Pac-Man ?",["Namco","Capcom","Konami","SNK"],0,"Pac-Man est créé par Namco et lancé en arcade en 1980.",[]),
  Q("J06","jeux","hard","Qui est le créateur initial de Minecraft ?",["Gabe Newell","Markus Persson","John Carmack","Tim Sweeney"],1,"Markus « Notch » Persson crée la première version de Minecraft.",[]),
  Q("J07","jeux","expert","Quels étaient les deux premiers jeux Pokémon commercialisés au Japon en 1996 ?",["Rouge et Bleu","Rouge et Vert","Or et Argent","Jaune et Bleu"],1,"Pokémon Rouge et Vert sortent au Japon en 1996.",[]),
  Q("J08","jeux","expert","En quelle année la première PlayStation est-elle commercialisée en Europe ?",["1994","1995","1996","1997"],1,"La PlayStation arrive en Europe en septembre 1995.",[]),
  Q("J09","jeux","easy","Comment s’appelle le frère de Mario ?",["Wario","Luigi","Toad","Yoshi"],1,"Luigi est le frère de Mario.",[]),
  Q("J10","jeux","easy","Quel studio est à l’origine de « Fortnite » ?",["Valve","Epic Games","Ubisoft","Bungie"],1,"Epic Games développe Fortnite.",["Epic"]),
  Q("J11","jeux","easy","Quel guerrier spartiate est le héros principal de « God of War » ?",["Kratos","Dante","Ryu","Marcus Fenix"],0,"Kratos est le protagoniste central de God of War.",[]),
  Q("J12","jeux","normal","Comment s’appelle la princesse du royaume d’Hyrule dans « The Legend of Zelda » ?",["Peach","Zelda","Midna","Samus"],1,"La princesse Zelda donne son nom à la série.",[]),
  Q("J13","jeux","normal","Sur quelle console est sorti le premier « Halo » en 2001 ?",["PlayStation 2","Xbox","GameCube","Dreamcast"],1,"Halo: Combat Evolved accompagne le lancement de la première Xbox.",[]),
  Q("J14","jeux","normal","Quelle entreprise commercialise la marque PlayStation ?",["Nintendo","Sega","Sony","Microsoft"],2,"PlayStation est une marque de Sony.",["Sony Interactive Entertainment"]),
  Q("J15","jeux","hard","Quel studio japonais a développé la série « Dark Souls » ?",["Capcom","FromSoftware","Square Enix","PlatinumGames"],1,"FromSoftware développe la série Dark Souls.",["From Software"]),
  Q("J16","jeux","hard","Quel studio développe « Red Dead Redemption 2 » ?",["Naughty Dog","Rockstar Games","Bethesda Game Studios","CD Projekt Red"],1,"Red Dead Redemption 2 est développé par Rockstar Games.",["Rockstar"]),
  Q("J17","jeux","expert","Quel jeu d’arcade d’Atari sorti en 1972 popularise un tennis de table minimaliste ?",["Asteroids","Pong","Breakout","Space Invaders"],1,"Pong devient l’un des premiers grands succès commerciaux du jeu vidéo.",[]),
  Q("J18","jeux","expert","Quel jeu de 1998 met le joueur dans la peau du scientifique Gordon Freeman ?",["System Shock 2","Half-Life","Quake II","Deus Ex"],1,"Gordon Freeman est le protagoniste de Half-Life.",["Half Life"]),
  Q("J19","jeux","easy","Quelle entreprise est historiquement associée à la série Super Mario ?",["Team Ico","Ion Storm","Nintendo","Cyan"],2,"Super Mario est une franchise de Nintendo.",[]),
  Q("J20","jeux","easy","Quel est le nom du héros en armure de la série Halo ?",["Master Chief","Gordon Freeman","Sans-Nom","Lara Croft"],0,"Master Chief est le protagoniste emblématique de Halo.",["John-117","John 117"]),
  Q("J21","jeux","easy","Quel dieu guerrier est le héros principal de la série God of War ?",["Kratos","Master Chief","Alucard","Sonic"],0,"Kratos est le héros principal de God of War.",[]),
  Q("J22","jeux","easy","Quelle archéologue est l'héroïne de Tomb Raider ?",["Lara Croft","Creeper","Master Chief","Zelda"],0,"Lara Croft est l'héroïne de Tomb Raider.",[]),
  Q("J23","jeux","easy","Quel ennemi vert de Minecraft explose lorsqu'il s'approche du joueur ?",["Zelda","Kratos","Creeper","Sonic"],2,"Le Creeper est un ennemi emblématique de Minecraft.",[]),
  Q("J24","jeux","easy","Quel hérisson bleu est la mascotte de Sega ?",["Sans-Nom","Sonic","Kratos","Zelda"],1,"Sonic est la mascotte de Sega.",[]),
  Q("J25","jeux","easy","Quelle princesse donne son nom à la série The Legend of Zelda ?",["Lara Croft","Sans-Nom","Creeper","Zelda"],3,"La princesse Zelda donne son nom à la série.",[]),
  Q("J26","jeux","normal","Comment s'appelle le protagoniste de Half-Life ?",["Sans-Nom","Gordon Freeman","Creeper","Master Chief"],1,"Gordon Freeman est le protagoniste de Half-Life.",[]),
  Q("J27","jeux","normal","Quel créateur est particulièrement associé à Metal Gear ?",["Ron Gilbert","Hideo Kojima","Richard Garriott","Éric Chahi"],1,"Hideo Kojima est le créateur emblématique de Metal Gear.",["Kojima"]),
  Q("J28","jeux","normal","Quel éditeur japonais est associé à la série Resident Evil ?",["FromSoftware","Ion Storm","Capcom","Nintendo"],2,"Resident Evil est une franchise de Capcom.",[]),
  Q("J29","jeux","normal","Quel studio développe la série Dark Souls ?",["Looking Glass Studios","FromSoftware","Team Ico","Naughty Dog"],1,"FromSoftware développe la série Dark Souls.",["From Software"]),
  Q("J30","jeux","normal","Quel studio a créé The Last of Us ?",["FromSoftware","Naughty Dog","Nintendo","BioWare"],1,"Naughty Dog a développé The Last of Us.",[]),
  Q("J31","jeux","normal","Quel studio est associé à Grand Theft Auto V ?",["Capcom","Cyan","Ion Storm","Rockstar Games"],3,"Rockstar Games est le studio/éditeur associé à GTA V.",["Rockstar"]),
  Q("J32","jeux","normal","Quel studio a créé la série Mass Effect ?",["Ion Storm","Capcom","BioWare","Looking Glass Studios"],2,"BioWare a créé Mass Effect.",["Bioware"]),
  Q("J33","jeux","normal","Dans Portal, quel laboratoire fictif sert de cadre principal ?",["Hyrule","Rapture","Midgar","Aperture Science"],3,"Aperture Science est le laboratoire fictif de Portal.",["Aperture"]),
  Q("J34","jeux","normal","Sur quelle console Chrono Trigger sort-il initialement en 1995 ?",["Super Nintendo","Dreamcast","PlayStation","Mega Drive"],0,"Chrono Trigger sort d'abord sur Super Famicom/Super Nintendo.",["SNES","Super Famicom"]),
  Q("J35","jeux","hard","Sur quelle console Sega sort-il Shenmue à l'origine ?",["Mega Drive","Dreamcast","PlayStation","Super Nintendo"],1,"Shenmue sort initialement sur Dreamcast.",[]),
  Q("J36","jeux","hard","Quel studio a développé le premier System Shock ?",["Rockstar Games","Konami","Looking Glass Studios","Cyan"],2,"System Shock a été développé par Looking Glass Technologies/Studios.",["Looking Glass"]),
  Q("J37","jeux","hard","Quel studio a développé le premier Baldur's Gate ?",["Cyan","BioWare","Nintendo","Konami"],1,"BioWare a développé le premier Baldur's Gate.",[]),
  Q("J38","jeux","hard","Quel studio a développé le premier Deus Ex ?",["Nintendo","Looking Glass Studios","Ion Storm","Capcom"],2,"Deus Ex a été développé par Ion Storm.",[]),
  Q("J39","jeux","hard","Quel éditeur japonais est à l'origine de la série Silent Hill ?",["Capcom","Konami","Rockstar Games","Looking Glass Studios"],1,"Silent Hill est une série lancée par Konami.",[]),
  Q("J40","jeux","hard","Quel personnage est le héros jouable de Castlevania: Symphony of the Night ?",["Creeper","Alucard","Lara Croft","Master Chief"],1,"Alucard est le protagoniste jouable principal de Symphony of the Night.",[]),
  Q("J41","jeux","hard","Sur quelle planète se déroule une grande partie du premier Metroid ?",["Aperture Science","Midgar","Zebes","Rapture"],2,"Le premier Metroid se déroule sur la planète Zebes.",[]),
  Q("J42","jeux","hard","Quel moteur est utilisé par le premier Half-Life ?",["Unity","Source","Unreal Engine","GoldSrc"],3,"Half-Life utilise le moteur GoldSrc, dérivé du moteur de Quake.",[]),
  Q("J43","jeux","hard","Quel studio a développé le premier Quake ?",["Looking Glass Studios","Naughty Dog","FromSoftware","id Software"],3,"Quake a été développé par id Software.",["id"]),
  Q("J44","jeux","hard","Quel studio japonais a développé Ico ?",["Ion Storm","Capcom","Team Ico","Cyan"],2,"Ico a été développé par Team Ico au sein de Sony Japan Studio.",[]),
  Q("J45","jeux","expert","Quel créateur français est l'auteur principal d'Another World ?",["Ron Gilbert","Richard Garriott","Éric Chahi","Hideo Kojima"],2,"Éric Chahi a conçu Another World.",["Eric Chahi","Chahi"]),
  Q("J46","jeux","expert","Quel créateur est associé à la série Ultima ?",["Hideo Kojima","Richard Garriott","Éric Chahi","Ron Gilbert"],1,"Richard Garriott est le créateur d'Ultima.",["Garriott"]),
  Q("J47","jeux","expert","Comment s'appelle le protagoniste de Planescape: Torment ?",["Gordon Freeman","Sans-Nom","Sonic","Zelda"],1,"Le protagoniste est The Nameless One, traduit Sans-Nom.",["The Nameless One","Nameless One"]),
  Q("J48","jeux","expert","Quel studio a créé Myst ?",["Nintendo","Cyan","Capcom","FromSoftware"],1,"Myst a été créé par Cyan.",["Cyan Worlds"]),
  Q("J49","jeux","expert","Quel concepteur est particulièrement associé à The Secret of Monkey Island ?",["Ron Gilbert","Éric Chahi","Richard Garriott","Hideo Kojima"],0,"Ron Gilbert est l'un des principaux créateurs de Monkey Island.",["Gilbert"]),
  Q("J50","jeux","expert","Quel studio a développé Shadow of the Colossus ?",["Looking Glass Studios","Ion Storm","Nintendo","Team Ico"],3,"Shadow of the Colossus a été développé par Team Ico.",[])
);
