QUESTIONS.push(
  Q("M01","musique","easy","Quel groupe vient de Liverpool ?",["The Beatles","ABBA","U2","Queen"],0,"Les Beatles se forment à Liverpool.",[]),
  Q("M02","musique","easy","Qui chantait principalement avec Queen ?",["David Bowie","Freddie Mercury","Elton John","George Michael"],1,"Freddie Mercury est le chanteur emblématique de Queen.",[]),
  Q("M03","musique","normal","De quel pays est originaire le duo Daft Punk ?",["Belgique","France","Royaume-Uni","Canada"],1,"Daft Punk est un duo français.",[]),
  Q("M04","musique","normal","Qui interprète l’album « Thriller » ?",["Prince","Michael Jackson","Stevie Wonder","Lionel Richie"],1,"Thriller est un album de Michael Jackson sorti en 1982.",["Jackson"]),
  Q("M05","musique","hard","Quel groupe interprète « Smells Like Teen Spirit » ?",["Pearl Jam","Nirvana","Soundgarden","Radiohead"],1,"Le titre ouvre l’album Nevermind de Nirvana.",[]),
  Q("M06","musique","hard","Quel groupe a sorti l’album « Abbey Road » ?",["The Rolling Stones","The Beatles","Pink Floyd","The Who"],1,"Abbey Road est un album des Beatles sorti en 1969.",[]),
  Q("M07","musique","expert","Combien de symphonies numérotées Beethoven a-t-il achevées ?",["7","8","9","10"],2,"Beethoven a achevé neuf symphonies numérotées.",[]),
  Q("M08","musique","expert","À quel pays Bob Marley est-il principalement associé par sa naissance et sa carrière ?",["Cuba","Jamaïque","Bahamas","Trinité-et-Tobago"],1,"Bob Marley est né en Jamaïque et est une figure majeure du reggae.",[]),
  Q("M09","musique","easy","Quel artiste est surnommé le « King of Pop » ?",["Prince","Michael Jackson","Elvis Presley","George Michael"],1,"Michael Jackson est couramment surnommé le King of Pop.",["Jackson"]),
  Q("M10","musique","easy","Combien de touches possède généralement un piano moderne standard ?",["61","76","88","96"],2,"Un piano acoustique moderne standard possède généralement 88 touches.",[]),
  Q("M11","musique","easy","Quel groupe interprète « Bohemian Rhapsody » ?",["Queen","Muse","The Who","U2"],0,"Bohemian Rhapsody est un morceau de Queen.",[]),
  Q("M12","musique","normal","Qui interprète « Like a Virgin » ?",["Madonna","Cyndi Lauper","Cher","Whitney Houston"],0,"Like a Virgin est l’un des grands succès de Madonna.",[]),
  Q("M13","musique","normal","Quel duo français interprète « One More Time » ?",["Air","Justice","Daft Punk","Cassius"],2,"One More Time est un titre de Daft Punk.",[]),
  Q("M14","musique","normal","De quel instrument Yo-Yo Ma est-il un virtuose ?",["Violon","Violoncelle","Piano","Flûte"],1,"Yo-Yo Ma est un violoncelliste de renommée internationale.",["Cello"]),
  Q("M15","musique","hard","Quel compositeur baroque est l’auteur des « Quatre Saisons » ?",["Bach","Vivaldi","Haendel","Telemann"],1,"Antonio Vivaldi compose Les Quatre Saisons.",["Antonio Vivaldi"]),
  Q("M16","musique","hard","Quel groupe a sorti l’album « The Dark Side of the Moon » ?",["Pink Floyd","Led Zeppelin","Genesis","Deep Purple"],0,"Pink Floyd publie The Dark Side of the Moon en 1973.",[]),
  Q("M17","musique","expert","Quel est le nom de scène de David Robert Jones ?",["David Bowie","Elton John","Sting","Morrissey"],0,"David Robert Jones adopte le nom de scène David Bowie.",["Bowie"]),
  Q("M18","musique","expert","Quel trompettiste de jazz est au centre de l’album « Kind of Blue » ?",["Louis Armstrong","Miles Davis","Chet Baker","Dizzy Gillespie"],1,"Miles Davis dirige les sessions de Kind of Blue.",["Davis"]),
  Q("M19","musique","easy","Quel chanteur était le leader de Nirvana ?",["Mick Jagger","Kurt Cobain","Ian Curtis","Richard D. James"],1,"Kurt Cobain était le chanteur et guitariste de Nirvana.",["Cobain"]),
  Q("M20","musique","easy","De quel pays est originaire U2 ?",["Suède","Islande","Irlande","Allemagne"],2,"U2 est un groupe irlandais formé à Dublin.",[]),
  Q("M21","musique","easy","De quel pays est originaire ABBA ?",["Irlande","Islande","Suède","Allemagne"],2,"ABBA est un groupe suédois.",["Suede"]),
  Q("M22","musique","easy","Quel chanteur est le leader historique des Rolling Stones ?",["Serge Gainsbourg","Kurt Cobain","Mick Jagger","Flea"],2,"Mick Jagger est le chanteur des Rolling Stones.",["Jagger"]),
  Q("M23","musique","easy","Qui interprète l'album « Like a Virgin » ?",["Madonna","Damon Albarn","Portishead","Kurt Cobain"],0,"Like a Virgin est un album de Madonna.",[]),
  Q("M24","musique","easy","Quel est le nom civil du rappeur Eminem ?",["Nas","Portishead","Richard D. James","Marshall Mathers"],3,"Eminem s'appelle Marshall Bruce Mathers III.",["Marshall Bruce Mathers","Marshall Mathers III"]),
  Q("M25","musique","easy","Sous quel nom est né Bob Dylan ?",["Nas","Robert Smith","Robert Zimmerman","Mick Jagger"],2,"Bob Dylan est né Robert Allen Zimmerman.",["Robert Allen Zimmerman"]),
  Q("M26","musique","normal","Quel groupe a sorti l'album « OK Computer » ?",["Portishead","John Coltrane","Radiohead","Kurt Cobain"],2,"OK Computer est un album de Radiohead.",[]),
  Q("M27","musique","normal","Quels frères sont au cœur du groupe Oasis ?",["Paul McCartney et John Lennon","Liam et Noel Gallagher","Mick Jagger et Keith Richards","Thomas Bangalter et Guy-Manuel de Homem-Christo"],1,"Oasis est notamment mené par les frères Liam et Noel Gallagher.",["Liam Gallagher et Noel Gallagher","Liam Noel Gallagher"]),
  Q("M28","musique","normal","Quel duo a sorti l'album « Random Access Memories » ?",["John Coltrane","Nas","Daft Punk","Serge Gainsbourg"],2,"Random Access Memories est un album de Daft Punk.",[]),
  Q("M29","musique","normal","De quelle ville anglaise Massive Attack est-il originaire ?",["Bristol","Amazonie","Arctique","Antarctique"],0,"Massive Attack s'est formé à Bristol.",[]),
  Q("M30","musique","normal","Qui interprète l'album « Back to Black » ?",["Nas","Amy Winehouse","Richard D. James","Serge Gainsbourg"],1,"Back to Black est un album d'Amy Winehouse.",["Winehouse"]),
  Q("M31","musique","normal","Quel est le surnom du bassiste Michael Balzary des Red Hot Chili Peppers ?",["Richard D. James","Flea","Portishead","Ian Curtis"],1,"Michael Balzary est connu sous le nom de Flea.",[]),
  Q("M32","musique","normal","Quel groupe a sorti « Master of Puppets » ?",["Metallica","Radiohead","Damon Albarn","Robert Zimmerman"],0,"Master of Puppets est un album de Metallica.",[]),
  Q("M33","musique","normal","Qui est le chanteur emblématique de The Cure ?",["Damon Albarn","Richard D. James","Flea","Robert Smith"],3,"Robert Smith est le chanteur et leader de The Cure.",["Smith"]),
  Q("M34","musique","normal","Quel musicien de Blur a co-créé Gorillaz ?",["Serge Gainsbourg","Damon Albarn","Kurt Cobain","Marshall Mathers"],1,"Damon Albarn a co-créé Gorillaz avec Jamie Hewlett.",["Albarn"]),
  Q("M35","musique","hard","Quel chanteur était le leader de Joy Division ?",["Ian Curtis","John Coltrane","Robert Zimmerman","Flea"],0,"Ian Curtis était le chanteur de Joy Division.",["Curtis"]),
  Q("M36","musique","hard","Quel groupe a sorti l'album « Dummy » ?",["Radiohead","Serge Gainsbourg","Portishead","Nas"],2,"Dummy est le premier album de Portishead.",[]),
  Q("M37","musique","hard","De quel pays est originaire Kraftwerk ?",["Irlande","Islande","Allemagne","Suède"],2,"Kraftwerk est un groupe allemand formé à Düsseldorf.",[]),
  Q("M38","musique","hard","De quel pays est originaire Björk ?",["Islande","Allemagne","Suède","Irlande"],0,"Björk est une artiste islandaise.",["Islande"]),
  Q("M39","musique","hard","Quel rappeur a sorti l'album « Illmatic » ?",["Miles Davis","Nas","Robert Smith","Daft Punk"],1,"Illmatic est le premier album de Nas.",[]),
  Q("M40","musique","hard","À quel arrondissement de New York le Wu-Tang Clan est-il particulièrement associé ?",["Staten Island","Amazonie","Antarctique","Sahara"],0,"Le Wu-Tang Clan est particulièrement associé à Staten Island.",[]),
  Q("M41","musique","hard","Quel est le nom civil d'Aphex Twin ?",["Robert Zimmerman","Richard D. James","Radiohead","Serge Gainsbourg"],1,"Aphex Twin est le pseudonyme de Richard D. James.",["Richard James"]),
  Q("M42","musique","hard","Quel trompettiste a sorti l'album « Kind of Blue » ?",["Miles Davis","Kurt Cobain","Serge Gainsbourg","Richard D. James"],0,"Kind of Blue est un album de Miles Davis.",["Davis"]),
  Q("M43","musique","hard","Quel saxophoniste a sorti « A Love Supreme » ?",["Richard D. James","Madonna","John Coltrane","Radiohead"],2,"A Love Supreme est une œuvre majeure de John Coltrane.",["Coltrane"]),
  Q("M44","musique","hard","Quel artiste français a sorti l'album « Histoire de Melody Nelson » ?",["Ian Curtis","Robert Smith","Miles Davis","Serge Gainsbourg"],3,"Histoire de Melody Nelson est un album de Serge Gainsbourg.",["Gainsbourg"]),
  Q("M45","musique","expert","Quel compositeur a écrit « Le Sacre du printemps » ?",["Philip Glass","Igor Stravinsky","John Cage","Claude Debussy"],1,"Le Sacre du printemps est une œuvre d'Igor Stravinsky.",["Stravinsky"]),
  Q("M46","musique","expert","Quel compositeur a écrit « La Mer » ?",["Claude Debussy","Philip Glass","Gustav Mahler","Igor Stravinsky"],0,"La Mer est une œuvre de Claude Debussy.",["Debussy"]),
  Q("M47","musique","expert","Quel compositeur a écrit le « Boléro » ?",["Gustav Mahler","John Cage","Claude Debussy","Maurice Ravel"],3,"Le Boléro est une œuvre de Maurice Ravel.",["Ravel"]),
  Q("M48","musique","expert","Quel compositeur a écrit la Symphonie n°5 dont l'Adagietto est célèbre ?",["John Cage","Gustav Mahler","Claude Debussy","Igor Stravinsky"],1,"L'Adagietto appartient à la Symphonie n°5 de Gustav Mahler.",["Mahler"]),
  Q("M49","musique","expert","Quel compositeur est l'auteur de la pièce silencieuse « 4′33″ » ?",["John Cage","Philip Glass","Claude Debussy","Igor Stravinsky"],0,"4′33″ est une œuvre de John Cage.",["Cage"]),
  Q("M50","musique","expert","Quel compositeur est une figure majeure du minimalisme américain avec Steve Reich ?",["John Cage","Maurice Ravel","Igor Stravinsky","Philip Glass"],3,"Philip Glass est une figure majeure du minimalisme musical.",["Glass"])
);
