QUESTIONS.push(
  Q("SP01","sport","easy","Combien de joueurs une équipe de football aligne-t-elle normalement sur le terrain au coup d’envoi ?",["9","10","11","12"],2,"Une équipe commence normalement avec 11 joueurs.",[]),
  Q("SP02","sport","easy","Quelle couleur porte le leader du classement général du Tour de France ?",["Verte","Jaune","Blanche","Rouge"],1,"Le maillot jaune distingue le leader du classement général.",[]),
  Q("SP03","sport","normal","Combien de joueurs une équipe de rugby à XV aligne-t-elle sur le terrain ?",["11","13","15","16"],2,"Le rugby à XV se joue à 15 joueurs par équipe.",[]),
  Q("SP04","sport","normal","Combien y a-t-il d’anneaux sur le symbole olympique ?",["4","5","6","7"],1,"Le symbole olympique est composé de cinq anneaux entrelacés.",[]),
  Q("SP05","sport","hard","À quelle hauteur réglementaire se trouve l’arceau de basket ?",["2,75 m","3,05 m","3,25 m","3,50 m"],1,"Le panier est à 10 pieds, soit environ 3,05 m.",[]),
  Q("SP06","sport","hard","Combien de tournois composent le Grand Chelem de tennis ?",["3","4","5","6"],1,"Open d’Australie, Roland-Garros, Wimbledon et US Open.",[]),
  Q("SP07","sport","expert","Quelle est la distance officielle d’un marathon ?",["40 km","41,195 km","42,195 km","43 km"],2,"Le marathon mesure officiellement 42,195 km.",[]),
  Q("SP08","sport","expert","Quel drapeau indique traditionnellement la fin d’une course automobile ?",["Rouge","Noir","À damier","Bleu"],2,"Le drapeau à damier marque l’arrivée.",[]),
  Q("SP09","sport","easy","Combien de joueurs d’une même équipe sont sur le terrain en basket-ball ?",["4","5","6","7"],1,"Une équipe de basket-ball aligne cinq joueurs sur le terrain.",[]),
  Q("SP10","sport","easy","Au tennis, quel score vient après 30 dans un jeu classique ?",["35","40","45","50"],1,"Le décompte classique passe de 30 à 40.",[]),
  Q("SP11","sport","easy","Quelle est la longueur d’un bassin olympique de natation ?",["25 m","33 m","50 m","100 m"],2,"Un bassin olympique mesure 50 mètres.",[]),
  Q("SP12","sport","normal","Combien de joueurs une équipe de volley-ball aligne-t-elle sur le terrain ?",["5","6","7","8"],1,"Une équipe de volley-ball compte six joueurs sur le terrain.",[]),
  Q("SP13","sport","normal","À quelle distance du but se trouve le point de penalty au football ?",["9 m","10 m","11 m","12 m"],2,"Le point de penalty est situé à 11 mètres de la ligne de but.",["11 mètres","11 metres"]),
  Q("SP14","sport","normal","Dans quel territoire se dispute le célèbre Grand Prix automobile de Monaco ?",["France","Italie","Monaco","Suisse"],2,"Le Grand Prix se déroule dans les rues de la principauté de Monaco.",[]),
  Q("SP15","sport","hard","Combien de manches réglementaires compte normalement un match de baseball professionnel ?",["7","8","9","10"],2,"Un match réglementaire de baseball se joue normalement en neuf manches.",["9 manches"]),
  Q("SP16","sport","hard","Combien d’épreuves composent un décathlon ?",["8","9","10","12"],2,"Le décathlon regroupe dix épreuves.",["10 épreuves","10 epreuves"]),
  Q("SP17","sport","expert","Quel est le poids réglementaire du poids masculin senior au lancer du poids ?",["5 kg","6 kg","7,26 kg","8 kg"],2,"Le poids masculin senior pèse 7,26 kg.",["7.26 kg","7,26","7.26"]),
  Q("SP18","sport","expert","À combien de points se joue normalement une manche de tennis de table moderne ?",["11","15","21","25"],0,"Une manche se joue normalement en 11 points, avec deux points d’écart requis.",["11 points"]),
  Q("SP19","sport","easy","Combien de joueurs une équipe de football aligne-t-elle sur le terrain au coup d'envoi ?",["11","9","170","13"],0,"Une équipe de football aligne 11 joueurs.",[]),
  Q("SP20","sport","easy","Combien de joueurs une équipe de rugby à XV aligne-t-elle ?",["5","21","15","25"],2,"Le rugby à XV se joue à 15 joueurs par équipe.",[]),
  Q("SP21","sport","easy","Combien de joueurs une équipe de handball aligne-t-elle sur le terrain, gardien compris ?",["170","7","9","13"],1,"Une équipe de handball aligne 7 joueurs.",[]),
  Q("SP22","sport","easy","Combien de joueurs une équipe de baseball aligne-t-elle en défense ?",["9","18","25","21"],0,"Une équipe de baseball aligne neuf joueurs en défense.",[]),
  Q("SP23","sport","easy","Quelle est la distance officielle d'un semi-marathon ?",["0,914 m","5,18 m","28 m","21,0975 km"],3,"Un semi-marathon mesure 21,0975 km.",["21.0975 km","21097,5 m"]),
  Q("SP24","sport","easy","À quelle hauteur se trouve l'arceau d'un panier de basket ?",["3,05 m","0,914 m","400","28 m"],0,"L'arceau est à 3,05 m du sol.",["3.05 m"]),
  Q("SP25","sport","easy","Combien d'anneaux comporte le symbole olympique ?",["5","6","15","170"],0,"Le symbole olympique comporte cinq anneaux.",[]),
  Q("SP26","sport","normal","À combien de points se joue normalement un set de badminton ?",["170","9","3","21"],3,"Un set de badminton se joue à 21 points, avec règles d'écart.",["21 points"]),
  Q("SP27","sport","normal","Combien de points vaut un essai au rugby à XV ?",["9","5","147","3"],1,"Un essai vaut 5 points au rugby à XV.",["5 points"]),
  Q("SP28","sport","normal","Combien de bases comporte un terrain de baseball en comptant le marbre ?",["7","9","4","25"],2,"Le parcours de baseball comporte quatre bases en comptant le marbre.",[]),
  Q("SP29","sport","normal","Combien de joueurs une équipe de hockey sur glace aligne-t-elle normalement sur la glace, gardien compris ?",["18","25","6","11"],2,"Une équipe aligne normalement six joueurs sur la glace, gardien compris.",[]),
  Q("SP30","sport","normal","Combien de trous compte un parcours de golf standard ?",["15","9","5","18"],3,"Un parcours standard compte 18 trous.",[]),
  Q("SP31","sport","normal","Quel est le break maximal standard au snooker sans boule libre exceptionnelle ?",["5","147","170","7"],1,"Le break maximal standard est de 147 points.",["147 points"]),
  Q("SP32","sport","normal","Combien d'armes sont utilisées en escrime sportive olympique ?",["9","3","170","15"],1,"L'escrime utilise trois armes : fleuret, épée et sabre.",[]),
  Q("SP33","sport","normal","Quelle distance fait un tour de piste d'athlétisme standard au couloir 1 ?",["400","3,05 m","0,914 m","28 m"],0,"Un tour de piste standard mesure 400 m.",["400 m","400 mètres"]),
  Q("SP34","sport","normal","Combien de joueurs une équipe de water-polo aligne-t-elle dans l'eau, gardien compris ?",["170","11","7","3"],2,"Une équipe de water-polo aligne sept joueurs dans l'eau.",[]),
  Q("SP35","sport","hard","Combien de joueurs une équipe de futsal aligne-t-elle sur le terrain, gardien compris ?",["5","170","25","4"],0,"Une équipe de futsal joue à cinq.",[]),
  Q("SP36","sport","hard","Combien de joueurs une équipe de rugby à XIII aligne-t-elle ?",["9","13","18","3"],1,"Le rugby à XIII se joue à treize joueurs.",[]),
  Q("SP37","sport","hard","Quelles deux disciplines combine le biathlon ?",["Cyclisme et escrime","Course et natation","Aviron et tir","Ski de fond et tir à la carabine"],3,"Le biathlon associe ski de fond et tir à la carabine.",["Ski et tir","Ski de fond tir"]),
  Q("SP38","sport","hard","Quelles trois disciplines composent un triathlon classique ?",["Natation, cyclisme et course à pied","Ski, luge et biathlon","Course, saut et lancer","Natation, aviron et cyclisme"],0,"Le triathlon combine natation, cyclisme et course à pied.",["Natation vélo course","Natation cyclisme course"]),
  Q("SP39","sport","hard","Quel est le checkout maximal possible en trois fléchettes aux darts ?",["170","21","11","9"],0,"Le checkout maximal en trois fléchettes est 170.",[]),
  Q("SP40","sport","hard","À combien de points se joue normalement un set de volley-ball, hors tie-break ?",["5","3","4","25"],3,"Un set classique de volley-ball se joue à 25 points.",["25 points"]),
  Q("SP41","sport","hard","Combien de joueurs une équipe de hockey sur gazon aligne-t-elle ?",["7","11","15","9"],1,"Le hockey sur gazon se joue à 11 joueurs.",[]),
  Q("SP42","sport","hard","Combien de joueurs composent une équipe de curling sur la glace ?",["4","6","13","21"],0,"Une équipe de curling compte quatre joueurs.",[]),
  Q("SP43","sport","hard","À combien de points se joue normalement un jeu de squash moderne ?",["147","9","11","5"],2,"Un jeu de squash se joue normalement à 11 points.",["11 points"]),
  Q("SP44","sport","hard","Combien d'épreuves comporte l'heptathlon ?",["13","7","21","147"],1,"L'heptathlon comporte sept épreuves.",[]),
  Q("SP45","sport","expert","Quelle est la hauteur du filet de tennis au centre ?",["0,914 m","5,18 m","3,05 m","28 m"],0,"Le filet de tennis mesure 0,914 m au centre.",["91,4 cm","0.914 m"]),
  Q("SP46","sport","expert","Quelle est la longueur réglementaire d'un terrain FIBA de basket-ball ?",["0,914 m","70 m","28 m","3,05 m"],2,"Un terrain FIBA mesure 28 m de long.",["28 mètres","28"]),
  Q("SP47","sport","expert","Quelle est la largeur d'un terrain de badminton en simple ?",["5,18 m","21,0975 km","0,914 m","70 m"],0,"La largeur en simple est de 5,18 m.",["5.18 m"]),
  Q("SP48","sport","expert","Quel est le poids du javelot masculin senior ?",["4 kg","7,26 kg","800 g","2 kg"],2,"Le javelot masculin senior pèse 800 g.",["0,8 kg","800 grammes"]),
  Q("SP49","sport","expert","Quel est le poids du disque masculin senior ?",["2 kg","800 g","7,26 kg","4 kg"],0,"Le disque masculin senior pèse 2 kg.",["2000 g"]),
  Q("SP50","sport","expert","À quelle distance se tire l'épreuve individuelle olympique de tir à l'arc en plein air ?",["5,18 m","3,05 m","21,0975 km","70 m"],3,"La distance olympique de référence est 70 m.",["70 mètres"])
);
