QUESTIONS.push(
  Q("T01","tech","easy","Que signifie HTML ?",["HyperText Markup Language","High Transfer Machine Link","Home Tool Markup Layer","Hyperlink Text Media Logic"],0,"HTML signifie HyperText Markup Language.",[]),
  Q("T02","tech","easy","Quels chiffres utilise le système binaire ?",["0 et 1","1 et 2","0 à 9","A et B"],0,"Le binaire utilise deux états : 0 et 1.",[]),
  Q("T03","tech","normal","Qui est à l’origine du noyau Linux ?",["Steve Wozniak","Linus Torvalds","Dennis Ritchie","Richard Stallman"],1,"Linus Torvalds commence le noyau Linux en 1991.",[]),
  Q("T04","tech","normal","En quelle année le premier iPhone est-il commercialisé ?",["2005","2006","2007","2008"],2,"Le premier iPhone est commercialisé en 2007.",[]),
  Q("T05","tech","hard","Qui a inventé le World Wide Web ?",["Vint Cerf","Tim Berners-Lee","Bill Gates","Alan Turing"],1,"Tim Berners-Lee propose le World Wide Web au CERN en 1989.",[]),
  Q("T06","tech","hard","Que signifie le « S » de HTTPS ?",["Simple","Secure","System","Shared"],1,"HTTPS est la version sécurisée de HTTP via chiffrement TLS.",[]),
  Q("T07","tech","expert","Qui a créé JavaScript en 1995 ?",["James Gosling","Brendan Eich","Guido van Rossum","Bjarne Stroustrup"],1,"Brendan Eich crée JavaScript chez Netscape en 1995.",[]),
  Q("T08","tech","expert","Quel type de mémoire perd généralement son contenu quand l’alimentation est coupée ?",["ROM","RAM","SSD","Blu-ray"],1,"La RAM classique est une mémoire volatile.",[]),
  Q("T09","tech","easy","Que signifie l’acronyme USB ?",["Universal Serial Bus","Unified System Base","User Service Bridge","Universal Signal Band"],0,"USB signifie Universal Serial Bus.",[]),
  Q("T10","tech","easy","Que signifie CPU en informatique ?",["Central Processing Unit","Computer Personal Utility","Core Program User","Central Peripheral Unit"],0,"CPU signifie Central Processing Unit.",["Processeur","Unité centrale de traitement","Unite centrale de traitement"]),
  Q("T11","tech","easy","Que signifie PNG dans le nom du format d’image ?",["Portable Network Graphics","Personal Numeric Graphic","Pixel Network Group","Public Network Grid"],0,"PNG signifie Portable Network Graphics.",[]),
  Q("T12","tech","normal","Comment s’appelait le premier navigateur web créé par Tim Berners-Lee ?",["Mosaic","WorldWideWeb","Netscape Navigator","Lynx"],1,"Le premier navigateur de Tim Berners-Lee s’appelait WorldWideWeb, puis Nexus.",["Nexus","World Wide Web"]),
  Q("T13","tech","normal","Que signifie SQL ?",["Simple Query Link","Structured Query Language","System Queue Logic","Standard Quick Language"],1,"SQL signifie Structured Query Language.",[]),
  Q("T14","tech","normal","Que signifie IP dans « adresse IP » ?",["Internet Protocol","Internal Port","Information Packet","Interface Process"],0,"IP signifie Internet Protocol.",[]),
  Q("T15","tech","hard","Qui a créé le système de gestion de versions Git ?",["Richard Stallman","Linus Torvalds","Ken Thompson","Guido van Rossum"],1,"Linus Torvalds crée Git en 2005.",["Torvalds"]),
  Q("T16","tech","hard","Que signifie TCP ?",["Transfer Control Package","Transmission Control Protocol","Terminal Connection Process","Transport Core Protocol"],1,"TCP signifie Transmission Control Protocol.",[]),
  Q("T17","tech","expert","Combien de bits composent un octet ?",["4","8","16","32"],1,"Un octet contient 8 bits.",["8 bits"]),
  Q("T18","tech","expert","Que signifie SHA dans des noms comme SHA-256 ?",["Secure Hash Algorithm","System Host Access","Sequential Hex Array","Secure Hardware Address"],0,"SHA signifie Secure Hash Algorithm.",[]),
  Q("T19","tech","easy","Que signifie CPU ?",["Secure Shell","Central Processing Unit","Portable Operating System Interface","Wide Area Network"],1,"CPU signifie Central Processing Unit.",[]),
  Q("T20","tech","easy","Que signifie CSS ?",["JavaScript Object Notation","Cascading Style Sheets","Graphics Processing Unit","Portable Document Format"],1,"CSS signifie Cascading Style Sheets.",[]),
  Q("T21","tech","easy","Que signifie URL ?",["Uniform Resource Locator","Domain Name System","Random Access Memory","Wide Area Network"],0,"URL signifie Uniform Resource Locator.",[]),
  Q("T22","tech","easy","Que signifie RAM ?",["Extensible Markup Language","Secure Shell","Random Access Memory","Wide Area Network"],2,"RAM signifie Random Access Memory.",[]),
  Q("T23","tech","easy","Que signifie GPU ?",["Extensible Markup Language","Central Processing Unit","Graphics Processing Unit","Uniform Resource Locator"],2,"GPU signifie Graphics Processing Unit.",[]),
  Q("T24","tech","easy","Que signifie USB ?",["Universal Serial Bus","Domain Name System","Cascading Style Sheets","Simple Mail Transfer Protocol"],0,"USB signifie Universal Serial Bus.",[]),
  Q("T25","tech","easy","Que signifie PDF ?",["Extensible Markup Language","Portable Document Format","Secure Shell","Uniform Resource Locator"],1,"PDF signifie Portable Document Format.",[]),
  Q("T26","tech","normal","Que signifie DNS ?",["Domain Name System","Central Processing Unit","Hypertext Transfer Protocol","JavaScript Object Notation"],0,"DNS signifie Domain Name System.",[]),
  Q("T27","tech","normal","Que signifie HTTP ?",["Hypertext Transfer Protocol","Uniform Resource Locator","Universal Serial Bus","JavaScript Object Notation"],0,"HTTP signifie Hypertext Transfer Protocol.",[]),
  Q("T28","tech","normal","Quel protocole cryptographique protège normalement une connexion HTTPS moderne ?",["UDP","SSL","TLS","IP"],2,"HTTPS repose aujourd'hui normalement sur TLS.",[]),
  Q("T29","tech","normal","Que signifie XML ?",["Extensible Markup Language","Portable Document Format","Portable Operating System Interface","Central Processing Unit"],0,"XML signifie Extensible Markup Language.",[]),
  Q("T30","tech","normal","Que signifie JSON ?",["Simple Mail Transfer Protocol","Graphics Processing Unit","Random Access Memory","JavaScript Object Notation"],3,"JSON signifie JavaScript Object Notation.",[]),
  Q("T31","tech","normal","Que signifie API ?",["Application Programming Interface","Random Access Memory","Simple Mail Transfer Protocol","Central Processing Unit"],0,"API signifie Application Programming Interface.",[]),
  Q("T32","tech","normal","Que signifie LAN ?",["Local Area Network","Basic Input/Output System","Graphics Processing Unit","Cascading Style Sheets"],0,"LAN signifie Local Area Network.",[]),
  Q("T33","tech","normal","Que signifie WAN ?",["Central Processing Unit","JavaScript Object Notation","Portable Document Format","Wide Area Network"],3,"WAN signifie Wide Area Network.",[]),
  Q("T34","tech","normal","Que signifie BIOS ?",["Basic Input/Output System","Hypertext Transfer Protocol","Uniform Resource Locator","Portable Operating System Interface"],0,"BIOS signifie Basic Input/Output System.",[]),
  Q("T35","tech","hard","Combien de bits contient une adresse IPv4 ?",["32","48","128","128 bits"],0,"Une adresse IPv4 contient 32 bits.",["32 bits"]),
  Q("T36","tech","hard","Combien de bits contient une adresse IPv6 ?",["128 bits","32","48","128"],3,"Une adresse IPv6 contient 128 bits.",["128 bits"]),
  Q("T37","tech","hard","Combien de bits contient typiquement une adresse MAC Ethernet classique ?",["128","48","32","128 bits"],1,"Une adresse MAC Ethernet classique fait généralement 48 bits.",["48 bits"]),
  Q("T38","tech","hard","Qui a créé Git ?",["Linus Torvalds","Brendan Eich","Guido van Rossum","James Gosling"],0,"Linus Torvalds a créé Git en 2005.",["Torvalds"]),
  Q("T39","tech","hard","En quelle année Linus Torvalds annonce-t-il le projet Linux ?",["1598","1991","1997","1713"],1,"Linus Torvalds annonce Linux en 1991.",[]),
  Q("T40","tech","hard","Qui a créé le langage Python ?",["Guido van Rossum","Brendan Eich","Dennis Ritchie","James Gosling"],0,"Guido van Rossum est le créateur de Python.",["Guido","Van Rossum"]),
  Q("T41","tech","hard","Qui est considéré comme le principal créateur du langage Java ?",["James Gosling","Guido van Rossum","Brendan Eich","Linus Torvalds"],0,"James Gosling est considéré comme le père de Java.",["Gosling"]),
  Q("T42","tech","hard","Qui a créé le langage C chez Bell Labs ?",["Brendan Eich","Guido van Rossum","James Gosling","Dennis Ritchie"],3,"Dennis Ritchie a créé le langage C.",["Ritchie"]),
  Q("T43","tech","hard","Qui a créé le langage JavaScript ?",["Linus Torvalds","Brendan Eich","Dennis Ritchie","James Gosling"],1,"Brendan Eich crée JavaScript en 1995.",["Eich"]),
  Q("T44","tech","hard","En quelle année Android 1.0 est-il commercialisé ?",["2012","1945","2008","2001"],2,"Le premier smartphone commercial sous Android 1.0 arrive en 2008.",[]),
  Q("T45","tech","expert","Que signifie POSIX ?",["Extensible Markup Language","Secure Shell","Domain Name System","Portable Operating System Interface"],3,"POSIX signifie Portable Operating System Interface.",[]),
  Q("T46","tech","expert","Que signifie SMTP ?",["Local Area Network","Secure Shell","Simple Mail Transfer Protocol","Cascading Style Sheets"],2,"SMTP signifie Simple Mail Transfer Protocol.",[]),
  Q("T47","tech","expert","Que signifie IMAP ?",["Internet Message Access Protocol","Portable Document Format","Hypertext Transfer Protocol","Application Programming Interface"],0,"IMAP signifie Internet Message Access Protocol.",[]),
  Q("T48","tech","expert","Que signifie SSH ?",["Extensible Markup Language","JavaScript Object Notation","Secure Shell","Wide Area Network"],2,"SSH signifie Secure Shell.",[]),
  Q("T49","tech","expert","Quelle est la taille de bloc d'AES ?",["48","128 bits","32","128"],1,"AES utilise des blocs de 128 bits.",["128"]),
  Q("T50","tech","expert","À quels trois noms correspondent les initiales RSA ?",["Jobs, Wozniak et Wayne","Gates, Allen et Ballmer","Rivest, Shamir et Adleman","Page, Brin et Schmidt"],2,"RSA porte les noms de Ron Rivest, Adi Shamir et Leonard Adleman.",["Rivest Shamir Adleman"])
);
